### ISSUE TITLE
Become a sponsor button not clickable 

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#105]
The become a sponsor button is not clickable because of the art placed above it

**Comment by mcturco** [comment]
I'm thinking we can just remove those two art components from this section, I don't feel like they are serving much purpose and are just getting in the way.

We just have to make sure that if we do this that the spacing is not too much on the bottom of this section and that it matches the top and bottom spacing of the speakers section as well

**Comment by AceTheCreator** [comment]
I'll try and fix it without removing those arts :)

**Comment by Ankitchaudharyy** [comment]
Hi @mcturco, Please assign this issue to me. I can work on this.
