### ISSUE TITLE
Fonts are not loading in properly on mobile devices

### ISSUE THREAD

**Issue by mcturco** [asyncapi/conference-website#106]
#### Describe the bug
Looking at the website on my phone and the fonts aren't loading properly :/ 

We should look into the tailwind config settings to see if there is anything we need to adjust to make sure they are loading in correctly.

![image](https://user-images.githubusercontent.com/60163079/192587460-c26bce06-c6e9-4c63-bbbb-80085d8a68a2.png)

**Comment by AceTheCreator** [comment]
@sambhavgupta0705 wanna look into this one?

**Comment by sambhavgupta0705** [comment]
Yeahh for sure ,just want to know which icons are being talked about here?

**Comment by PRABHU-OFFICIAL** [comment]
I can contribute to it 
I want to contribuye through winter of code 3.0 ☺

**Comment by AceTheCreator** [comment]
@PRABHU-OFFICIAL kindly join the slack channel and introduce yourself https://asyncapi.com/slack-invite

**Comment by AceTheCreator** [comment]
> Yeahh for sure ,just want to know which icons are being talked about here?

She means the fonts not icons

**Comment by sambhavgupta0705** [comment]
Well Ace I am not able to understand the issue 😅,as I think the font is looking fine

**Comment by AnimeshKumar923** [comment]
@mcturco I just discovered that the fonts are loading properly now.
You can close this issue from your side. Thank you 😊
![Screenshot_2023-04-21-20-41-10-20_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/99868037/233672290-e70c72db-1711-4d59-8bdb-205d3c792ef1.jpg)
