### ISSUE TITLE
fix: typos in speaker cards for AsyncAPI Conference 2022

### ISSUE THREAD

**Issue by alequetzalli** [asyncapi/conference-website#113]
1/3 of our speaker cards this year have typos. This issue lists the speaker cards with typos/punctuation errors that must be fixed. _(a couple of these were speaker submission errors)_

**Please carefully select the CORRECTED text below to address all typos:**

1. "How AsyncAPI Got a Facelift: GSoD 2022 Contributions" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Alejandra_how_asyncAPI_docs_got_facelift_gsod_2022_contributions.png)
2. "How Contributing to AsyncAPI Tools Inspired a Career in OSS" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Florence_how_contributing_to_asyncAPI_tools_inspired_a_career_in_oss.png)
3. "From Discovery to Implementation: Using the AsyncAPI Ecosystem for your Event-Driven Architecture" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Hugo_from_discovery_to_implementation_using_the_asyncAPI_ecosystem_for_your_event_driven_architecture.png)
4. "The Future of Messaging? Store-Carry-Forward (SCF) Protocols, Delay Tolerant Networks, and AsyncAPI" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Ismael_the_future_of_messaging_SCF_protocols_delay_tolerant_networks_asyncAPI.png)
5. "The Intricacies of a Single Keyword in AsyncAPI" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Jonas_the_intricacies_of_a_single_keyword_in_AsyncAPI.png)
6. "Contract Driven Development in AsyncAPI: Tools and Procedures" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Enrique_contract_driven_development_in_asyncAPI_tools_and_procedures.png) **This one the speaker submitted with wrong punctuation**
7. "Automating Governance for Asynchronous APIs" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Nauman_automating_goverance_for_asynchronous_APIs.png)
8. "A Beginner's Guide to Generator Tool Use-Cases" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Pratik_A_beginner's_guide_to_generator_tool_use_cases.png)
9. "AsyncAPI and Event API Products: a Match Made in Heaven" (https://raw.githubusercontent.com/asyncapi/conference-website/master/public/speaker_cards/Tamimi%26Jesse_asyncAPI_and_event_API_products_a_match_made_in_heaven.png)

**Comment by alequetzalli** [comment]
Here you go @Mayaleeeee, here is the detailed bug issue for speaker card errors.

Thank you for your OSS contribution 😄✨✨

**Comment by Mayaleeeee** [comment]
I'm so sorry about that @alequetzalli 😀😀🙈

Thanks for calling my attention to it, I'll be fixing it soon.🙏🙏

**Comment by alequetzalli** [comment]
It's ok, Live and Learn 😀!

Next time we’ll help review more thoroughly and **now you know to always use Grammarly even in design** 🙂

**Comment by derberg** [comment]
@Mayaleeeee, before you work on fixes, we need to double-check with official proposals from speakers. Because for example in case of `Contract Driven Development in AsyncAPI: Tools and Procedures` I actually think it should be `Contract Driven Development in AsyncApi, tools and procedures` as the presenter wanted it, I think `AsyncApi, tools and procedures` is a list. We can make grammar/name fixed, capitalization, but I think that is all. 

@alequetzalli do you still have access to cfp list?

**Comment by Mayaleeeee** [comment]
No probs @derberg

**Comment by derberg** [comment]
right @alequetzalli 😄 

Number | Suggested change | Original text from cfp
--- | --- | ---
1 | `How AsyncAPI Got a Facelift: GSoD 2022 Contributions` | `How AsyncAPI Docs got a Facelift: GSoD 2022 Contributions`
2 | `How Contributing to AsyncAPI Tools Inspired a Career in OSS` | `How contributing to AsyncAPI tools inspired a career in OSS`
3 | `From discovery to implementation: Using the AsyncAPI ecosystem for your Event-Driven Architecture` | `From discovery to implementation: Using the AsyncAPI ecosystem for your Event-Driven Architecture`
4 | `The Future of Messaging? Store-Carry-Forward (SCF) Protocols, Delay Tolerant Networks, and AsyncAPI` | `The Future of Messaging? "Store-Carry-Forward" (SCF) Protocols, Delay Tolerant Networks and AsyncApi`
5 | `The Intricacies of a Single Keyword in AsyncAPI` | `The Intricacies of a Single Keyword in AsyncAPI`
6 | `Contract Driven Development in AsyncAPI: Tools and Procedures` | `Contract Driven Development in AsyncApi, tools and procedures`
7 | `Automating Governance for Asynchronous APIs` | `Automating Governance for Asynchronous APIs`
8 | `A Beginner's Guide to Generator Tool Use-Cases` | `A Beginner's Guide to Generator Tool Use-cases`
9 | `AsyncAPI and Event API Products: a Match Made in Heaven` | `AsyncAPI and Event API Products; a Match Made in Heaven`

I think only in the case of **1** suggestion we need improvement = `How AsyncAPI Got a Facelift: GSoD 2022 Contributions` as I think it is missing `Docs`

> @derberg Good question! I did not think it was a list and I felt confused. If you are sure it's a list then that one can be left as is. 😃

yeah, I'm not 100% sure after reading CFP text, so let's stay with your proposal 😅

**Comment by alequetzalli** [comment]
yes! thanks for catching that mistake, @derberg .. my talk should def include the word `docs` 

cool 😎

**Comment by Mayaleeeee** [comment]
Nice @derberg @alequetzalli 
I'm on it.

**Comment by Mayaleeeee** [comment]
I have made the corrections @derberg @alequetzalli 

![Alejandra_how_asyncAPI_docs_got_a_facelift_gsod_2022_contributions](https://user-images.githubusercontent.com/105395613/197044663-b167bbe1-1778-4386-abc4-168675c781a4.png)

![Florence_how_contributing_to_asyncAPI_tools_inspired_a_career_in_oss](https://user-images.githubusercontent.com/105395613/197044945-7b20525c-ffb6-4075-8fef-fa983c1c7483.png)

![Hugo_from_discovery_to_implementation_using_the_asyncAPI_ecosystem_for_your_event_driven_architecture](https://user-images.githubusercontent.com/105395613/197045163-30975c34-aac0-46b9-9e67-39e3e239cf91.png)

![Ismael_the_future_of_messaging_SCF_protocols_delay_tolerant_networks_asyncAPI](https://user-images.githubusercontent.com/105395613/197045301-1a684e6b-adbd-48b5-93c3-c967b005e7f9.png)

![Jonas_the_intricacies_of_a_single_keyword_in_AsyncAPI](https://user-images.githubusercontent.com/105395613/197045575-1492c4a1-09e3-43b8-a358-f04a01f6e8bf.png)

![Enrique_contract_driven_development_in_asyncAPI_tools_and_procedures](https://user-images.githubusercontent.com/105395613/197045899-53fa5c6a-966b-4224-bc00-9b2eea4ddc3a.png)

![Nauman_automating_goverance_for_asynchronous_APIs](https://user-images.githubusercontent.com/105395613/197045974-8041fc8e-22e2-4d0d-b012-76751f83dc52.png)


![Pratik_A_beginner's_guide_to_generator_tool_use_cases](https://user-images.githubusercontent.com/105395613/197046080-14233230-d33c-4d4a-a48c-9f562dee3551.png)


![Tamimi Jesse_asyncAPI_and_event_API_products_a_match_made_in_heaven](https://user-images.githubusercontent.com/105395613/197046173-6dc098cd-14c0-4bdd-a49e-55ecd6704b30.png)

**Comment by alequetzalli** [comment]
Hey @Mayaleeeee There is still a mistake in my card, you have used a zero in place of the letter `o`.

<img width="893" alt="Screen Shot 2022-10-24 at 4 39 11 PM" src="https://user-images.githubusercontent.com/19964402/197650119-d8d1d0b0-2382-4f91-9ab0-dd7cfc2da8ae.png">

**Comment by Mayaleeeee** [comment]
Hy @alequetzalli sorry about that.

I have changed it in the PR I created today, lemme send it here so you can see it.

**Comment by alequetzalli** [comment]
All the rest of the cards are good now! thank you for your contribution 😄✨✨✨

**Comment by Mayaleeeee** [comment]
![ale](https://user-images.githubusercontent.com/105395613/197650704-d4e04200-fb09-4047-b5db-f0b687a7596a.png)

**Comment by alequetzalli** [comment]
yay!!!!! 🎉🙌🏽🎉🙌🏽🎉🙌🏽🎉🙌🏽
