### ISSUE TITLE
 Update Default Readme.md File to Meaningful Content

### ISSUE THREAD

**Issue by Savio629** [asyncapi/conference-website#149]
#### Describe the bug
 Update Default Readme.md File to Meaningful Content
 
 Link to conference website: [conference.asyncapi.com](https://conference.asyncapi.com/)

#### Expected behavior
You can get a reference from asyncapi/website's readme file : https://github.com/asyncapi/website#readme

**Comment by DarrenDsouza7273** [comment]
Can i work on this issue @Savio629

**Comment by Savio629** [comment]
Yeah @DarrenDsouza7273 👍
@AceTheCreator

**Comment by Savio629** [comment]
@DarrenDsouza7273 If you are struggling with determining the points for the readme
You can use this readme that I have configured

---

## What is AACoT?

AsyncAPI Conf on Tour (AACoT) is a way for you to experience the excitement and energy of this series of micro-conferences hosted around the globe, where the brightest minds and most passionate enthusiasts gather to share their knowledge and explore the latest developments in the field.

## Overview

This repository contains the sources of AsyncAPI Conference website:

- It's powered by [Next.js](https://nextjs.org/),
- It uses [Tailwind](https://tailwindcss.com/) CSS framework,
- It's build and deployed with [Netlify](https://www.netlify.com/).

## Requirements

Use the following tools to set up the project:

- [Node.js](https://nodejs.org/) v16.0.0+
- [npm](https://www.npmjs.com/) v7.10.0+


## Run locally

1. Fork the repository by clicking on `Fork` option on top right of the main repository.

2. Open Command Prompt on your local computer.

3. Clone the forked repository by adding your own GitHub username in place of `<username>`.  For multiple contributions it is recommended to have [proper configuration of forked repo](https://github.com/asyncapi/community/blob/master/git-workflow.md).

 ```bash
     git clone https://github.com/<username>/conference-website/
 ```

4. Navigate to the website directory.

 ```bash
     cd conference-website
 ```

5. Install all website dependencies. 

 ```bash
     npm install
 ```

6. Run the website locally.

 ```
     npm run dev
```

7. Access the live development server at [localhost:3000](http://localhost:3000).


### Spin up Gitpod codespace

In order to prepare and spin up a Gitpod dev environment for our project, we configured our workspace through a [.gitpod.yml](./.gitpod.yml) file.

To spin up a Gitpod codespace, go to http://gitpod.io/#https://github.com/asyncapi/conference-website.

### Build

To build a production-ready website, run the following command:

```bash
npm run build
```

Generated files of the website go to the `.next` folder.




## Submit your talk!

Fill up the form to apply as a speaker through [AsyncAPI Conference website](http://conference.asyncapi.com/ "AsyncAPI Conference website")



```text
  ├── Your Information                     # Your details 
  ├── Session Information                # Session title and description 
  ├── Session Format                       # Session format and level
  ├── Additional Information           # Special request to organizers
```







This project follows the [all-contributors](https://github.com/all-contributors/all-contributors) specification. Contributions of any kind welcome!

**Comment by Savio629** [comment]
I don't know if we need the `Run Locally` section
