### ISSUE TITLE
Implement Agenda Page

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#162]
Speakers for London have been selected, and we need to start working on the agenda page for AACoT'23 London.

@Mayaleeeee [made some awesome designs for this](https://www.figma.com/proto/sS5ofLRtuFqDGFvlNBurns/AACoT?type=design&node-id=817-884&t=wvHkqwlhQmI6K4BO-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=817%3A720&mode=design), we just need to in cooperate it to the conference website.

cc @AceTheCreator @thulieblack

**Comment by CatherineKiiru** [comment]
Hi @thulieblack is this issue still open? I'd like to work on it

**Comment by CatherineKiiru** [comment]
Thanks for the feedback. Are there other open issues in this particular project that I can work on?

**Comment by AceTheCreator** [comment]
@CatherineKiiru here's one https://github.com/asyncapi/conference-website/issues/170

**Comment by CatherineKiiru** [comment]
> @CatherineKiiru here's one #170

I've seen it's already taken. I'll browse through other issues. If you have others coming up, I'd love to work on them too.
