### ISSUE TITLE
Add all speakers button

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#163]
## Problem

When you're in the speaker's section on the homepage, it initially loads all the speakers for all venues, and then you can filter by venue. The problem is you can't go back to view all speakers because there's no "All" button after filtering. 

![AsyncAPI-Conference (3)](https://github.com/asyncapi/conference-website/assets/40604284/1506746d-1570-472e-9113-3b0d429708e0)

## Solution

Add an "All" button to the list and it should be active by default.

**Comment by Sky-De** [comment]
Hi there
I would like to work on this issue
@AceTheCreator assign this to me
Thanks

**Comment by AceTheCreator** [comment]
@Sky-De you can go ahead and work on it :)

**Comment by ansharora28** [comment]
Hey! @Sky-De 
Are you still working on this?

**Comment by ansharora28** [comment]
@AceTheCreator can I work on this since I couldn't find an associated PR? Thanks!

**Comment by AceTheCreator** [comment]
@ansharora28, yes you can :)

**Comment by Sylvie-Wxr** [comment]
@AceTheCreator Hi, i have created a PR. Can help review it? Thanks a lot.
