### ISSUE TITLE
 Implement visual states for images on location cards (hovered and clicked) 

### ISSUE THREAD

**Issue by Mayaleeeee** [asyncapi/conference-website#170]
#### Reason/Context
There is no effect when users hover or click on the location cards. 

#### Description
Implement visual states for images to improve user experience. This enhancement will help users understand what's happening by elevating the cards when hovered over and appropriately responding when clicked on. 

Here's a short recording  of how the section looks:
 
[331feb3d-22c6-434b-9c03-481a09148ab6.webm](https://github.com/asyncapi/conference-website/assets/105395613/2fbd4a17-8add-49f5-a8d9-346130a782b6)

**Comment by SoNiC-HeRE** [comment]
Can i work on this? @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> Can i work on this? @Mayaleeeee 

Yes, you can.
Thank you. 🤗
