### ISSUE TITLE
Change the font size used for the header on the Conference Website.

### ISSUE THREAD

**Issue by Mayaleeeee** [asyncapi/conference-website#175]
#### Reason/Context
The current font size is regular text, but it should be a header.

![Screenshot 2023-08-28 203543](https://github.com/asyncapi/conference-website/assets/105395613/a9c3d5c0-7b72-4b7b-aec6-6e1421610c62)

#### Description
Please increase the font size and make it bold. **Set the font size to 88x, line height to 80px, and letter spacing to -3, as** shown in the image below.

![Screenshot 2023-08-28 210725](https://github.com/asyncapi/conference-website/assets/105395613/562a36af-97f7-4259-b69d-cf88db8549d5)

**Comment by SoNiC-HeRE** [comment]
Can i work on this issue? @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> Can i work on this issue? @Mayaleeeee 
> 

Yes, please.
