### ISSUE TITLE
Paris Conference - Apply as a Speaker don't work

### ISSUE THREAD

**Issue by Ferror** [asyncapi/conference-website#179]
#### Describe the bug

Paris Conference - Apply as a Speaker doesn't work. IDK if that is because it is not working, or stopped working.
https://conference.asyncapi.com/venue/Paris#sponsors

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

<img width="1512" alt="Screenshot 2023-08-31 at 14 14 52" src="https://github.com/asyncapi/conference-website/assets/17534504/e27981e4-251c-4111-b14d-db1efb7e1792">

**Comment by AceTheCreator** [comment]
@Ferror, thanks for reporting this, but unfortunately, CFP for Paris has not opened yet.

**Comment by ankur0904** [comment]
@AceTheCreator Can I work on this issue?
