### ISSUE TITLE
Add ticket form button for Madrid page

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#188]
Since we won't be introducing a ticket fee for [AACoT'23 Madrid](https://conference.asyncapi.com/venue/Madrid), we need to add a button that links [to this form](https://docs.google.com/forms/d/e/1FAIpQLSdwqi27LpsIi8tKQoQBcUWDUJZi0be0cHpWnDtWhhHVn00hFA/viewform) where we will collect the information for interested participants who want to attend the conference, as we have a limited number of tickets. 
 
 This will be similar to 👇🏿
![image](https://github.com/asyncapi/conference-website/assets/66913810/c4521d17-6308-4fff-b278-e36190a47562)

But we will rename it to **Tickets Form**

**Comment by ivangsa** [comment]
Hi, I wouldn't make it a tickets button but a survery, so we can gather information about how many people is interested in attending in person.. (as we know we have limited seats..)

**Comment by Sylvie-Wxr** [comment]
Hey, I would like to work on this issue, but is this already resolved in issue 185?  @vishvamsinh28

**Comment by vishvamsinh28** [comment]
Yo @Sylvie-Wxr that's a different issue

**Comment by vishvamsinh28** [comment]
@thulieblack @AceTheCreator i have made some changes in this #185 PR, It will fix this issue also

**Comment by thulieblack** [comment]
Why is the button transparent? is that how it should be cc @AceTheCreator @Mayaleeeee 

![image](https://github.com/asyncapi/conference-website/assets/66913810/d1e0974e-41d1-4299-8b03-7525117815fe)

I suggest maintaining the button color throughout the website, but I'm not a design expect please help

![image](https://github.com/asyncapi/conference-website/assets/66913810/ef272746-df9d-4fa2-9111-4435356472bd)

**Comment by vishvamsinh28** [comment]
@thulieblack i implemented Maya's design

**Comment by thulieblack** [comment]
It's not visible enough when it's this transparent, or maybe it's my eyes

**Comment by vishvamsinh28** [comment]
@Mayaleeeee @thulieblack @AceTheCreator what changes should i make ?

**Comment by AceTheCreator** [comment]
> It's not visible enough when it's this transparent, or maybe it's my eyes

I agree with you @thulieblack. @Mayaleeeee your input is needed :)

**Comment by thulieblack** [comment]
Hey @vishvamsinh28 could you please update the button link to this👉🏿 https://forms.gle/9vVbiYTNeWhoQHHU9

**Comment by vishvamsinh28** [comment]
Yea sure. Should I also change button style ?

**Comment by thulieblack** [comment]
yes please but let me ping @Mayaleeeee first

**Comment by Mayaleeeee** [comment]
Thanks for bringing it to my attention, @thulieblack @AceTheCreator.  Let's go with our primary button as shown below, @vishvamsinh28.

![Madrid_Location (2)](https://github.com/asyncapi/conference-website/assets/105395613/e2c75288-f115-42b0-a43d-e46b5284dd27)

**Comment by thulieblack** [comment]
whats the progress on this PR?

**Comment by vishvamsinh28** [comment]
@thulieblack almost done, I was busy with some college work but i will push latest changes in next commit today or tomorrow

**Comment by thulieblack** [comment]
No worries was just checking in 😊. please take care
