### ISSUE TITLE
issue with talk submission

### ISSUE THREAD

**Issue by derberg** [asyncapi/conference-website#201]
I tried to use https://conference.asyncapi.com/venue/bangalore

so I filled in all data, and before submitting I was "damn, I will loose talk description if the submission fails, so will click `back` to copy my stuff"

clicking back, shows empty form, data is not remembered and do not stay in the form 😭

**Comment by derberg** [comment]
@AceTheCreator btw you're still using https://sheet.best - what about "expiration" issues we saw last time?

**Comment by thulieblack** [comment]
yes, we used https://sheet.best because the deadline is just 2/3 weeks. The rest is @AceTheCreator fault🤣🤣🤣🤣🤣🤣🤣

**Comment by AceTheCreator** [comment]
> so I filled in all data, and before submitting I was "damn, I will loose talk description if the submission fails, so will click `back` to copy my stuff"

Yea, I never really thought they'll be a need for that 😄

I'll create an issue for it and label it `hacktoberfest` :)

**Comment by AceTheCreator** [comment]
> @AceTheCreator btw you're still using https://sheet.best - what about "expiration" issues we saw last time?

Yea, cuz Thulie said it's only gonna be up for a few weeks, so I thought we should just stick with sheet.best(30days)
