### ISSUE TITLE
venues addresses to be clickable links that take you you google map location

### ISSUE THREAD

**Issue by derberg** [asyncapi/conference-website#202]
like in title, basically every venua has a string with address

would be nice if this is a link to google maps to a pin to location

long term even nicer would be to have embedded map, but I guess separate issue for discussion

**Comment by Mayaleeeee** [comment]
Thanks for bringing up this issue, @derberg 

I was close to raising the same concern because I felt frustrated and reluctant to manually copy the location text and paste it onto the map just to see the event's location.

**Comment by Mithilesh-create** [comment]
I would like to contribute to this issue. Please Assign this to me.

**Comment by IAmRiteshKoushik** [comment]
Has this issue been resolved already or does it still need work ? If yes, then I would like to work on it.

**Comment by AceTheCreator** [comment]
I'm closing this issue cuz it's not relevant anymore
