### ISSUE TITLE
Venue sub menu doesn't close

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#205]
When you click on the venue dropdown, it should close when you click anywhere on the page.

![AsyncAPI-Conference (4)](https://github.com/asyncapi/conference-website/assets/40604284/9d247d9e-99ad-48cd-b9cb-06bd5e2c1b0a)

**Comment by PrasathHari** [comment]
I would like to pick this up

**Comment by AceTheCreator** [comment]
@PrasathHari you go ahead and work on it :)

**Comment by ayushnau** [comment]
https://github.com/asyncapi/conference-website/pull/212

**Comment by ayushnau** [comment]
@PrasathHari 
here is the pr for it. sorry i was working on it from before.

**Comment by ShashwatPS** [comment]
Is it possible for me to work on this issue, as it has not been resolved yet ?

**Comment by AceTheCreator** [comment]
Hey @ShashwatPS 

Please go ahead :) you can use the existing PR as a starting point
