### ISSUE TITLE
would be nice if venue from past events is grayed out

### ISSUE THREAD

**Issue by derberg** [asyncapi/conference-website#208]
When you go to conference.asyncapi.com you see `Venues` section

I think that it would be nice if for past events, given venue is somehow grayed out, or have some water mark like `ended` 🤔 

@Mayaleeeee wdyt? how that should be done? just grayed out?

**Comment by Mayaleeeee** [comment]
Thank you, Lukasz. I appreciate your input. 

Here's what I think;

1. I agree that reducing the opacity by greying it out would be a good idea. Additionally, we could include the text "Ended or Completed" beside the date in the venue section and the venue page before the location's name. I have attached some images for your reference. Please take a look and let me know your thoughts.

Beside the date
![Screenshot 2023-10-02 121928](https://github.com/asyncapi/conference-website/assets/105395613/d9931545-dbb8-4d17-bb93-ffcddd71397e)

Before the name
![Screenshot 2023-10-02 122031](https://github.com/asyncapi/conference-website/assets/105395613/36b25e22-e1b9-4cf9-b160-d450c69836bb)
 

2. We could have a new "Upcoming Events" and "Past Events" section before the speakers' section, with a layout as shown in the reference image.
![WhatsApp Image 2023-10-02 at 12 34 35 PM](https://github.com/asyncapi/conference-website/assets/105395613/e0fd18d2-fada-4c96-808e-2c4dbfd985f5)

**Comment by derberg** [comment]
> We could have a new "Upcoming Events" and "Past Events" section before the speakers' section, with a layout as shown in the reference image.

sounds good, but I guess it is a separate issue?

**Comment by Mayaleeeee** [comment]
> > We could have a new "Upcoming Events" and "Past Events" section before the speakers' section, with a layout as shown in the reference image.
> 
> sounds good, but I guess it is a separate issue?

Yes.

**Comment by derberg** [comment]
@Mayaleeeee I will mark this issue as /gfi js
and put it up for hacktoberfest and point 1 is defined. For the other great idea please open a separate issue.

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee I will mark this issue as /gfi js and put it up for hacktoberfest and point 1 is defined. For the other great idea please open a separate issue.

Alright, I will.
Thank you.

**Comment by Arbtrage** [comment]
Hey  @Mayaleeeee , I would like to work on this issue.

**Comment by derberg** [comment]
go ahead 🙏

**Comment by Arbtrage** [comment]
Hi @derberg , I saw that in the date field there was no particular format follow. I was thinking of using Date module to compare the dates, but found dissimilar date formats. Like in one event there is a range and others have a single date. 
I am a bit confused as to how to approach this new format. Can you provide some suggestions ?

For example,
London: ""September 20, 2023""
Paris: "December 6-8, 2023"

Should I use regex expression for this or traverse the string to look for range format ?

**Comment by derberg** [comment]
hey, not a codeowner here

@AceTheCreator please have a look

**Comment by Arbtrage** [comment]
I have added a tag `Ended` after the date for the events that are already over. 
I figured that there can be two types of events:
- Single day
- 2 or more days

I created a function where it would hadle these two cases and return whether the event has passed or not. According to that returned value the `Ended` tag is being added.

Let me know if I need to make some UI changes or apply another Logic.

@AceTheCreator @derberg 

<img width="818" alt="image" src="https://github.com/asyncapi/conference-website/assets/100552235/e9d962e1-f895-4c40-ab9a-7289518c3f20">

**Comment by Mayaleeeee** [comment]
Still relevant

**Comment by monoMonu** [comment]
@AceTheCreator @Mayaleeeee 

I have made the required changes and added a function, which compares the present date and event date to decide the tag for the event (from Upcoming and Ended). Also fades the text color of past events. This is specific to the current format of date used in the cityList.json file.
I tested the code by changing the date of one of the events as you can see...because there were only upcoming events.

I have also removed the "apply to be a speaker" button from the past events as it has no use there.

Please review the PR and if there is any other changes needed, then please let me know

**Comment by Mayaleeeee** [comment]
> @AceTheCreator @Mayaleeeee
> 
> I have made the required changes and added a function, which compares the present date and event date to decide the tag for the event (from Upcoming and Ended). Also fades the text color of past events. This is specific to the current format of date used in the cityList.json file. I tested the code by changing the date of one of the events as you can see...because there were only upcoming events.
> 
> I have also removed the "apply to be a speaker" button from the past events as it has no use there.
> 
> Please review the PR and if there is any other changes needed, then please let me know

I have just left a comment on the PR. Thank you.
