### ISSUE TITLE
introducing a section on the conference website for upcoming and past events

### ISSUE THREAD

**Issue by Mayaleeeee** [asyncapi/conference-website#211]
**Reason/Context:**
- **Why do we need this improvement?** To enhance user experience and streamline the process.

- **How will this change help?** This section will simplify users' interaction by providing easy access to event details, registration information, and resources from previous events.

- **What is the motivation?** To improve efficiency and user satisfaction.

**Description:**
- **What changes have to be introduced?** Minor UI adjustments for clarity.
- **Will this be a breaking change?** No, it's not.
- **How could it be implemented/designed?** Refine UI elements and update user flows.
 
I have created a rough sketch on paper to guide what we expect for the design below. However, if you have a better idea, please share it.
![271959680-e0fd18d2-fada-4c96-808e-2c4dbfd985f5](https://github.com/asyncapi/conference-website/assets/105395613/ab94c6f0-f1c0-43d6-a532-2d0a1dff4d16)

**Comment by Mayaleeeee** [comment]
Can we add this as a Hacktoberfest issue for designers? I couldn't do it because I didn't have access. cc @derberg, @AceTheCreator, and @thulieblack.

**Comment by AceTheCreator** [comment]
Yea, i can just add the label for you :)

**Comment by Mayaleeeee** [comment]
> Yea, i can just add the label for you :)

Thank you.

**Comment by Thehussayn** [comment]
hey Maya, i am interested in creating the designs proposed

**Comment by Mayaleeeee** [comment]
> I'm interseted in it...
> 

Please go ahead

**Comment by Mayaleeeee** [comment]
> hey Maya, i am interested in creating the designs proposed
> 

In case @PUNEET-EMM is not available to work on it, you can go ahead.

**Comment by Mayaleeeee** [comment]
> hey Maya, i am interested in creating the designs proposed
> 

Thanks, @Thehussayn

**Comment by Thehussayn** [comment]
Hello.
I designed the lo-fi for the task, Kindly check it out and give a review.

https://www.figma.com/file/DBZwsJkRM4VcHra3SkYwmZ/AsyncAPI-conf-des?type=design&node-id=0-1&mode=design&t=NwY1pqlTii9ybWnT-0

**Comment by thulieblack** [comment]
@Mayaleeeee, is this relevant to the current website?

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee, is this relevant to the current website?
> 

Nope
