### ISSUE TITLE
Hamburger menu does not close by clicking outside of it

### ISSUE THREAD

**Issue by ravi2048** [asyncapi/conference-website#214]
#### Describe the bug
The hamburger menu does not close by clicking Escape button or clicking outside of the menu. The only way currently is to click on the close button.

#### How to Reproduce
Go to homepage on smaller screens to make hamburger icon to appear.
Click on hamburger icon.
Click outside of opened window, it does not close.

#### Expected behavior
For a better user experience, it should get closed by clicking outside or Esc key press.

**Comment by PUNEET-EMM** [comment]
I am interested in it
