### ISSUE TITLE
BUG : Unhandled Runtime Error

### ISSUE THREAD

**Issue by Vibgitcode27** [asyncapi/conference-website#215]
#### Describe the bug
There is Unhandled Runtime Error that pops up . This happens beacause we are trying to access the classList property of a DOM element that is null at the time of access.

If you ever conditionally render the elements that the refs are attached to, there might be cases where the element isn't in the DOM, and thus, the ref would be null.

#### How to Reproduce
Steps to reproduce the issue. 

-  Click on venue button present on Navabar.
- Choose any location.
- Then click on AACoT'23 logo which has "./' route for home page. An error message pop-up. 

I have shared a screenshot so that you can better understand the bug

### 📌 Request for Assignment:

I'd like to work on this issue. Please assign it to me. Please add hacktober fest label for me. Thanks.

- Screenshots ![Screenshot 2023-10-09 194701](https://github.com/asyncapi/conference-website/assets/110909159/e8ef0140-aa70-49d0-8326-30e2163db4cd)
- Link to GitHub repository with project that has issues :  https://github.com/asyncapi/conference-website/blob/master/components/Countdown/countdown.js
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

#### Expected behavior
There should not be any Unhandled Runtime Errors.

**Comment by AceTheCreator** [comment]
@Vibgitcode27 we do not assign issues, kindly go ahead and work on it :)

**Comment by Vibgitcode27** [comment]
Thank you! @AceTheCreator. I have created a pull request and it requires your kind review.
