### ISSUE TITLE
update twitter icon and add interactions

### ISSUE THREAD

**Issue by Mayaleeeee** [asyncapi/conference-website#223]
#### Reason/Context
1. The current Twitter icon in the footer has become obsolete and should be replaced with a new "X" icon to align with the latest branding guidelines.

2. The footer lacks user interaction, with neither icons nor text responding to user actions, such as hover or click events.  

#### Description
 1. Update the Twitter icon in the footer to the new "X" icon and ensure the new icon maintains the website's visual consistency and branding.
 2. Implement hover and click interactions for icons and text in the footer. Icons and text elements like the "**Code of Conduct" and the "logo "** should provide visual feedback when users interact with them.

![Screenshot 2023-10-13 115349](https://github.com/asyncapi/conference-website/assets/105395613/7b009b56-f4bf-4145-90f4-9c35e3d0a03a)

cc @AceTheCreator, please label it as an hacktoberfest issue.

**Comment by MahendraDani** [comment]
@Mayaleeeee 
I would like to work on this issue

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee 
> I would like to work on this issue

Please, go ahead. @MahendraDani
