### ISSUE TITLE
Conference Globe Now Black and White

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#246]
The conference globe is now black and white instead of having the website colors.

cc @AceTheCreator 

![image](https://github.com/asyncapi/conference-website/assets/66913810/6e9ec497-8b57-4c45-9a4e-dd16082436a8)

**Comment by Santhoshmani1** [comment]
Hai @thulieblack.
I have fixed the issue, will be happy to send a pull request if it's good.

### Old globe view
![Screenshot 2023-12-08 174516](https://github.com/asyncapi/conference-website/assets/119673958/715587bb-3889-4491-aade-d1c73c69f0ed)

### New globe view
![Screenshot 2023-12-08 174920](https://github.com/asyncapi/conference-website/assets/119673958/05278c5f-ab76-40b9-b8ae-9963814a950b)

**Comment by thulieblack** [comment]
@Santhoshmani1 the globe used to be these primary colors, and I suggest that even if we incorporate a new design, we need to maintain the website color palette
![image](https://github.com/asyncapi/conference-website/assets/66913810/01a0a208-cc50-452e-aa44-ffb1684131f1)
