### ISSUE TITLE
Update The Conference Website To 2024

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#259]
It's a New year; it's time to update our website to reflect the changes and additions for 2024. These are some of the necessary updates and improvements needed on the website, i.e., archiving the 2023 content, adding new venue information, speaker slides from the previous event, and incorporating a sponsorship page.

1. I would like us to archive and preserve the 2023 content for historical reference while making room for the new year's updates.
- On the 2023 content, we add speaker slides, especially for the locations that never had live streaming #204 

2. Update the website to 2024

-  Start adding confirmed venues on the website 

- Add a sponsorship page on the website that details the tiers we have, benefits information and redirects to the open collective page

- Structure our Call for Speaker form early 

There is plenty to mention; additionally, we can still maintain the current designs and improve from what we have.

cc @Mayaleeeee @AceTheCreator

**Comment by 120EE0980** [comment]
I would like to work on this issue.

**Comment by thulieblack** [comment]
which one @120EE0980 as I listed a number of issues

**Comment by RamGoel** [comment]
hey 
[@Thulie](https://asyncapi.slack.com/team/U03CNJPMT7C)
I have setup this project. As far as I understood the issue description . I think these will be changes on the home page.
I need more clarity for the venue page and other things. Can you help me with this. (edited)

**Comment by RamGoel** [comment]
Hey @thulieblack 
I have setup this project. As far as I understood the issue description . I think these will be changes on the home page. I need more clarity for the venue page and other things. Can you help me with this.


![image](https://github.com/asyncapi/conference-website/assets/71088429/75bae1e5-d887-412f-8448-1f85718f9f83)

**Comment by thulieblack** [comment]
Hi, @RamGoel; yes, we need to update the homepage and information to 2024. But before that, I propose we archive the 2023 content to "_previous editions or past editions_". 

@Mayaleeeee and @AceTheCreator your opinions on this

**Comment by RamGoel** [comment]
Ok I'll try to build something and raise a Draft PR. Give me some time.

**Comment by RamGoel** [comment]
Hello @thulieblack, Please have a look at the video below. I have used the components we already have to create a archive section.

- Automatic & manual scroll in speakers slider
- returns 404 if the year is not in archive. (e.g., 2022)
- Year wise title for pages (Image attached)
- Removed agenda as it might not be relevant for past editions.

Let me know, incase you need any other change.

https://github.com/asyncapi/conference-website/assets/71088429/80b65931-43eb-4e58-82c4-cac0c589a3f2

<img width="203" alt="image" src="https://github.com/asyncapi/conference-website/assets/71088429/145e4e07-da5c-4735-ab7a-156085b3f0c3">

**Comment by thulieblack** [comment]
Great job @RamGoel, some additions on the Past Editions:

1. We would like to add links to the recorded talks for [Madrid](https://www.youtube.com/playlist?list=PLbi1gRlP7pihD-7XYb6c9wcTdkavDzF3_) and [Bangalore](https://www.youtube.com/playlist?list=PLbi1gRlP7pijVocLZS7FeWKA4NBzJa7_Z)
2. We would also want to add a section for speaker slide decks #204

**Comment by RamGoel** [comment]
Made this CTA Link for Recorded Talks. 
I am raising a PR for this work. 

As the section you guys want is for overall website not specific to edition. So let's take it in another PR, which I'll raise in a day or two.


<img width="253" alt="image" src="https://github.com/asyncapi/conference-website/assets/71088429/5a28521e-cf44-44e8-8238-42a311b09a49">

**Comment by thulieblack** [comment]
The Recorded Talks can go to the same section as the slides. But lets get the PR going for now

**Comment by RamGoel** [comment]
> The Recorded Talks can go to the same section as the slides. But lets get the PR going for now

Thanks @thulieblack. We'll modify it later. You guys can review the code. Let me know if you guys need any revisions.

**Comment by sagarkori143** [comment]
@thulieblack I'm also interested to work on this. Please let me know if I can do something parallelly or assist @RamGoel in the tasks mentioned. Thanks!

**Comment by sagarkori143** [comment]
Okay @thulieblack . I'll surely work on it. I also have a suggestion for the speakers section on homepage of every year's conference website. Since the no of speaker can go huge, we should truncate the speakers list and add a button beneath the list to load more of them. If you agree with this, I can start working. Thanks!

**Comment by sagarkori143** [comment]
One more suggestion: As the paris tour has alson been ended. Either we should remove this button or can disable it:


![image](https://github.com/asyncapi/conference-website/assets/129517558/33bd1530-f81e-44a1-a9e6-53d77608ed98)

**Comment by thulieblack** [comment]
> Since the no of speaker can go huge, we should truncate the speakers list and add a button beneath the list to load more of them. If you agree with this, I can start working. Thanks!

Sure that will be something to consider once we have all the changes working.


> One more suggestion: As the paris tour has alson been ended. Either we should remove this button or can disable it

Yes, we will disable it for now but it'll be something for the person who is update the homepage as everything that's there needs to be changed. We have new venues dates etc.

**Comment by thulieblack** [comment]
@sagarkori143 have you started working on a PR yet for the sponsorship page?

**Comment by Satakshijain** [comment]
I would like to work on this issue

**Comment by sagarkori143** [comment]
Hey @thulieblack I had some health issues. Now I'm ready to go. Give me some more clarification about what I can do now?
