### ISSUE TITLE
Card text is unreadable 

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#266]
- The texts on the location images are difficult to read.

![h](https://github.com/asyncapi/conference-website/assets/105395613/d1c0231a-68c9-4a00-9f4e-8084c3be1428)

Instead, we could have something like the one below; you can check it in the Figma file [here](https://www.figma.com/file/sS5ofLRtuFqDGFvlNBurns/AsyncAPI-Conference-on-Tour'23%2FAACoT?type=design&node-id=1457%3A1002&mode=design&t=MkiKZWZHWuXJFlDO-1).
![Paris](https://github.com/asyncapi/conference-website/assets/105395613/eb5e4154-a118-4461-a77a-525206d6dbfe)

**Comment by devilkiller-ag** [comment]
Hey @AceTheCreator Can I work on this?

**Comment by AceTheCreator** [comment]
Sure, @devilkiller-ag

**Comment by techmannih** [comment]
@AceTheCreator 
I want to work on this issue, can you assign me.

**Comment by kalpesh-d** [comment]
Is this issue is fixed now?
