### ISSUE TITLE
Unaligned hero section

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#267]
the distance between the elements in the hero section should be the same length as the [previous year](https://conference.asyncapi.com/). 

![Screenshot 2024-02-27 224431](https://github.com/asyncapi/conference-website/assets/105395613/36af95c1-bdba-4fc8-8e23-1a30d4bf5dd6)

**Comment by helios2003** [comment]
Hey @AceTheCreator can I take it up?

**Comment by AceTheCreator** [comment]
Sure! @helios2003

**Comment by helios2003** [comment]
@AceTheCreator could you please explain the issue in a bit more detail? Since the link you provided also opens up the AsyncAPI 2024 conference itself.

**Comment by RamGoel** [comment]
@helios2003 You can get idea from [2022 archive](https://conference.2022.asyncapi.com/)

**Comment by RamGoel** [comment]
Anyone who is working on it, please consider fixing the mobile view dropdown alignment as well.

![image](https://github.com/asyncapi/conference-website/assets/71088429/2f24dad4-3f06-4656-84fd-129d4c0c00f4)
