### ISSUE TITLE
Footer Section not aligned

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#268]
The footer section is not responsive on mobile. 

![footer](https://github.com/asyncapi/conference-website/assets/40604284/ee2ddc10-2bad-4c44-8d91-d242f24792c6)

**Comment by Shubhamm-V** [comment]
Hey @AceTheCreator  I would like to work on this issue...! Can you assign it to me.

**Comment by AceTheCreator** [comment]
@Shubhamm-V, we don't assign issues; feel free to work on it if you're interested :)
