### ISSUE TITLE
[FEATURE] Adding a carousel to the venue card

### ISSUE THREAD

**Issue by utnim2** [asyncapi/conference-website#285]
### Why do we need this improvement?

Adding a carousel to the venue card so that user can navigate to the desired venue quickly

### How will this change help?

This will make the navigation to the required venue a lot easier

### Screenshots

![image](https://github.com/asyncapi/conference-website/assets/127925465/db6ec396-852a-4939-8603-954c5d3df376)

### How could it be implemented/designed?

This could be implemented by adding a carousel at the bottom or at the right and left of the screen

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by IAmRiteshKoushik** [comment]
Is this issue still open or has can it be closed ? The tasks underneath seemed to have been completed. @utnim2

**Comment by utnim2** [comment]
@thulieblack can i get your opinion on this

**Comment by thulieblack** [comment]
@Mayaleeeee

**Comment by AceTheCreator** [comment]
@utnim2, I'm glad you suggested this idea, but i don't think it's needed cuz we don't have many venues. I'm gonna close this issue :)
