### ISSUE TITLE
[FEATURE] Add the Subscribe section and button as in AACoT'23 site

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#298]
### Why do we need this improvement?

To make more people subscribe to AsyncAPI newsletter.

### How will this change help?

It will increase the subscribers in the AsyncAPI newsletter, who will come for the AACoT'24 event.

### Screenshots

![Screenshot from 2024-04-02 12-29-39](https://github.com/asyncapi/conference-website/assets/69006513/d8824e25-c6e7-4b33-a48d-49ef5f01e80b)

### How could it be implemented/designed?

Utilising the previous code from the AACoT'23 website to not change the design rules and usign realiable components rather than creating new ones from scratch.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by ashmit-coder** [comment]
Hey @Mayaleeeee I would like to ask for suggestion on where should we place this button.

In my opinion it would fit perfectly in the home page, with the same design as in the AACoT'23 website.

**Comment by AceTheCreator** [comment]
Hey Ashmit, wanna work on it?

**Comment by ashmit-coder** [comment]
> Hey Ashmit, wanna work on it?

Yeah sure Ace, was awaiting for a reply from Mayaleee, but ig will do it first then get it reviewed by you

**Comment by Mayaleeeee** [comment]
> > Hey Ashmit, wanna work on it?
> 
> Yeah sure Ace, was awaiting for a reply from Mayaleee, but ig will do it first then get it reviewed by you

Yes, please.

Let's have it.

**Comment by Mayaleeeee** [comment]
> Hey @Mayaleeeee I would like to ask for suggestion on where should we place this button.
> 
> In my opinion it would fit perfectly in the home page, with the same design as in the AACoT'23 website.

Thanks you.
It make sense @ashmit-coder 

Let's have it!
