### ISSUE TITLE
Add Conference Speakers and Agenda 

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#299]
Start adding the confirmed speakers plus bio and preparing for the agenda announcements.

- [x] Helsinki
- [x] London
- [ ] Paris

**Comment by Mayaleeeee** [comment]
I thought you added me as an assignee to this task last week @thulieblack. Did I get unassigned?

**Comment by thulieblack** [comment]
It was this task @Mayaleeeee #300

**Comment by Mayaleeeee** [comment]
> It was this task @Mayaleeeee #300 

Ohh, alright.
Thanks, Thulie. 🤗🥰
