### ISSUE TITLE
Speaker cards for social media

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#300]
Design speaker cards template the will be used to promote talks and shared on social media

- [x] Helsinki
- [x] London 
- [x] Paris

**Comment by thulieblack** [comment]
hey Maya, have you had a chance to work on this yet?

**Comment by Mayaleeeee** [comment]
> hey Maya, have you had a chance to work on this yet?

Hey Thulie👋

No, I haven't. I have been super busy throughout last week and this week.

Is it okay to get it done by next week?

**Comment by Mayaleeeee** [comment]
Hello @thulieblack
Here are the social media speaker cards for the Helsinki conference.

- Hugo - Getting Started With Event Driven Architecture & AsyncAPI
![Hugo](https://github.com/asyncapi/conference-website/assets/105395613/58b9e6e0-a3ef-46f7-82f3-0be77610ba49)

- Hugo - Using Test Containers for AsyncAPI Unit Testing and Mocking
 
 
![Uploading Hugo-Using Test Containers for AsyncAPI Unit Testing and Mocking.png…]()

-

**Comment by thulieblack** [comment]
Please also share the speaker card design link @Mayaleeeee

**Comment by thulieblack** [comment]
Thank you @Mayaleeeee
