### ISSUE TITLE
[BUG]: Description of Tickets Sale and Event and Host Sponsor is not visible.

### ISSUE THREAD

**Issue by techmannih** [asyncapi/conference-website#302]
### Describe the bug.

Hello @
Description of Tickets Sale and Event and Host Sponsor is not visible in between 700px to 590px. you can check 

### Expected behavior

Description of Tickets Sale and Event and Host Sponsor is  visible completely in between 700px to 590px. you can check 

### Screenshots

before 
![Screenshot 2024-04-05 105451](https://github.com/asyncapi/conference-website/assets/125847751/978a351b-4181-4792-8aa4-d5f992fa1fb4)
![Screenshot 2024-04-05 105439](https://github.com/asyncapi/conference-website/assets/125847751/67304674-d709-4b3c-9908-8512954e86e6)

after
![Screenshot 2024-04-05 114457](https://github.com/asyncapi/conference-website/assets/125847751/3168b57d-784f-4073-bca9-dbbcf51fdd8c)
![Screenshot 2024-04-05 114447](https://github.com/asyncapi/conference-website/assets/125847751/fca2c562-0fcc-4b8a-a7fd-c40806d2a590)

### How to Reproduce

1. first check with all pixels
2. add new class of width style 

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by AceTheCreator** [comment]
Nice catch @techmannih
