### ISSUE TITLE
[BUG] Error with width settings in tailwind config.

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#313]
There seems to be an issue with the tailwind config file.
In my opinion `grid grid-cols-2 lg:grid-cols-1` is working inversely.

    screens: {
			    xl: { max: '1279px' },
			    lg: { max: '1118px' },
			    sm: { max: '590px' },
		    },

to correct this the suggested chabge is

    screens: {
			    xl: '1279px' ,
			    lg: '1118px',
			    sm: '590px',
		    },

_Originally posted by @ashmit-coder in https://github.com/asyncapi/conference-website/pull/311#discussion_r1567351162_

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator I would like to get your opinion on this issue.

**Comment by AceTheCreator** [comment]
Do you really think this change is needed?

**Comment by ashmit-coder** [comment]
> Do you really think this change is needed?

Yeah no IMO, cause this is like a breaking change and will require a lot of rework for the site.

**Comment by ashmit-coder** [comment]
Closing this issue due to breaking changes
