### ISSUE TITLE
Add Gravitee Logo as Financial Sponsor

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#324]
Add the Gravitee Logo on the conference website as our Finacial Sponsor.

![Image](https://github.com/asyncapi/conference-website/assets/66913810/1b0b4e19-de9f-48a8-975b-75d4187896bf)

**Comment by ketansahugit** [comment]
Hey, I'd like to work on this issue but could you please elaborate, where exactly do you want the logo? is it below the "Apidays" logo?

**Comment by thulieblack** [comment]
Yes it can go below APIdays Logo with a heading "Financial Sponsors"
