### ISSUE TITLE
[FEATURE] Resolve the existing Next.js lint issues

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#328]
### Why do we need this improvement?

To improve the lint flow of the website and put proper checks in place.

**`NOTE`: **This is a breaking change hence, when you work on this make sure to not dirupt the functionality****

### How will this change help?

It will make better use of Next.js components and hence improve in website performance.

### Screenshots

![Screenshot from 2024-04-09 10-50-05](https://github.com/asyncapi/conference-website/assets/69006513/71ecb9f5-614d-41b1-81c0-3cfcb2bbf0fe)

### How could it be implemented/designed?

1. Lint the code using the `npm run lint` command. 
2. Resolve the warnings that occur in the terminal.
3. Resources to follow  https://nextjs.org/docs

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

### Suppoerted issues

https://github.com/asyncapi/conference-website/issues/306

### Supported PR

https://github.com/asyncapi/conference-website/pull/307

**Comment by kavania2002** [comment]
Hi @ashmit-coder, I would like to contribute in this issue. I'm new to open source and I think I would like to give it a try.

**Comment by ashmit-coder** [comment]
> Hi @ashmit-coder, I would like to contribute in this issue. I'm new to open source and I think I would like to give it a try.

Sure go ahead 😊

**Comment by 95481** [comment]
hi @ashmit-coder , i would like to  contribute .

**Comment by ashmit-coder** [comment]
Hey @95481 sorry but @kavania2002 is working on it if he is unable to complete it you can pick up the task

**Comment by kavania2002** [comment]
Hey @ashmit-coder, I have updated the code accordingly. Please have a look into it.
Thanks!
