### ISSUE TITLE
[FEATURE] The AsyncAPI logo in the footer should redirect to the landing page

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#338]
### Why do we need this improvement?

Do make use of the footer logo

### How will this change help?

Makes redirection easier for visitors

### How could it be implemented/designed?

Just an href should be assigned to the logo in the footer

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

None

**Comment by kavania2002** [comment]
Hey, I would like to work on this issue. Thanks!
