### ISSUE TITLE
[BUG] Decrease the top padding in subscribe section in mobile view

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#342]
### Describe the bug.

The top padding in the subscribe section is way too much for the mobile view.

### Expected behavior

The padding should be less and more  symmetrical

### Screenshots

![Screenshot from 2024-07-06 14-45-44](https://github.com/asyncapi/conference-website/assets/69006513/63104152-8ee6-4a0d-b05f-47ef3e8b2b08)

### How to Reproduce

1. Open the conference website in mobile view.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by ALIPHATICHYD** [comment]
Hey @ashmit-coder can I be assigned to this issue.

**Comment by ashmit-coder** [comment]
Hey @ALIPHATICHYD sure go ahead with it

**Comment by ALIPHATICHYD** [comment]
Alright, Thank you 🤩.

**Comment by anuragnegi000** [comment]
on it

**Comment by ashmit-coder** [comment]
Hey @anuragnegi000  the pr looks good but @ALIPHATICHYD was trying to work on it. Its not a good act on your side.

Though am not closing the pr, unless @ALIPHATICHYD submits a pr

**Comment by anuragnegi000** [comment]
@ashmit-coder  
that's totally fine but I saw your message on Slack saying "feel free to raise a PR." I thought this meant it was first come, first serve for PRs, so I didn't wait for the issue to be assigned to me.

**Comment by ashmit-coder** [comment]
> @ashmit-coder  
> that's totally fine but I saw your message on Slack saying "feel free to raise a PR." I thought this meant it was first come, first serve for PRs, so I didn't wait for the issue to be assigned to me.

Fair enough but do consider if someone else is requesting the issue, from the next time.

**Comment by anuragnegi000** [comment]
@ashmit-coder  Thank you for considering me. I'll make sure to be careful next time.

**Comment by ALIPHATICHYD** [comment]
> Hey @ALIPHATICHYD sure go ahead with it

Done
