### ISSUE TITLE
[BUG] <Hover Effects on Buttons and Nav Bar>

### ISSUE THREAD

**Issue by SagarSharma2809** [asyncapi/conference-website#356]
### Describe the bug.

Its a simple thing but makes the website look more interactive. 

Register Button , Subscribe button at footer and nav bar items doesn't have any effect on hovering and website looks very static.
 

### Expected behavior

Nav bar items can have a little hover effect: text color change on hover to make it look more interactive.

Register Button , Subscribe button at footer can have background color and text color change on hover.

Hover Effect should match website theme

### Screenshots

https://github.com/user-attachments/assets/f0033064-273f-49a4-8dab-82b43dc8d3fd

### How to Reproduce

1. I first did this
2. I then did this
3. And so on . . . 

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Mayaleeeee** [comment]
I like this @SagarSharma2809
Thank you for reporting the issue. However, I couldn't see the changes in the screen recording you sent. Did I miss something?

**Comment by SagarSharma2809** [comment]
Hi, @Mayaleeeee 
I thought to first raise the issue before working on this, thus the video was only to share what buttons hover effects needed. 

I am willing to work on it and add hover effects matching with website theme

**Comment by Mayaleeeee** [comment]
> Hi, @Mayaleeeee Thank You,
> I thought to first raise the issue before working on this, thus the video was only to share what buttons hover effects needed. 
> 
> I am willing to work on it and add hover effects matching with website theme

That's awesome @SagarSharma2809 
Please go ahead and work on it.

**Comment by SagarSharma2809** [comment]
Hi @Mayaleeeee I have submitted a Pull Request, Pls check

**Comment by Saurabhchaudhary9799** [comment]
I have raises a pull request for this issue , and i have uploaded the screen recording for this issue . Please check and revert back .

**Comment by Saurabhchaudhary9799** [comment]
I have raises a pull request  again for this issue because of some types issue in PR , and i have uploaded the screen recording for this issue . Please check and revert back .
