### ISSUE TITLE
[FEATURE] No hover effect in Meet the speakers button

### ISSUE THREAD

**Issue by anuragnegi000** [asyncapi/conference-website#363]
### Why do we need this improvement?

It will look professional as minor changes also matters a lot 

### How will this change help?

Nothing much but it will enhance the finishing of website

### Screenshots

https://github.com/user-attachments/assets/5fbc8510-70c2-4efa-a007-7ce9c823ba4e

### How could it be implemented/designed?

it just need a hover property.

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

None

**Comment by anuragnegi000** [comment]
can i work on this? @Mayaleeeee

**Comment by Mayaleeeee** [comment]
@anuragnegi000 
Are you sure this is not a duplicate issue? Because I can see this functionality on the conference website already.
