### ISSUE TITLE
The speaker announcement design

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#376]
We need a template for the speaker announcement. It will be used to showcase speakers on social media

# Please Follow 👇🏿

## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design.

**Comment by miracle-E** [comment]
I'd like to jump on this too @thulieblack @Mayaleeeee

**Comment by miracle-E** [comment]
![Speaker_announcement](https://github.com/user-attachments/assets/77ea4f77-8af5-41f3-94d8-60e84b2abde0)
@Mayaleeeee @thulieblack Kindly check out this draft.

**Comment by thulieblack** [comment]
@iambami please review

**Comment by Mayaleeeee** [comment]
> ![Speaker_announcement](https://github.com/user-attachments/assets/77ea4f77-8af5-41f3-94d8-60e84b2abde0)
> @Mayaleeeee @thulieblack Kindly check out this draft.

Looks good @iambami 

We can go with it.

**Comment by Mayaleeeee** [comment]
Thanks for your contributions @miracle-E

**Comment by miracle-E** [comment]
Alright. I will work on the update. Thank you

**Comment by miracle-E** [comment]
![Speaker-Announcement](https://github.com/user-attachments/assets/d51dd361-1e0d-4680-a08d-d7cb71f3a1d8)
Here @Mayaleeeee

**Comment by AceTheCreator** [comment]
@miracle-E @thulieblack @Mayaleeeee I'm adding the #hacktoberfest label to this. @miracle-E kindly register at https://hacktoberfest.com/ to make it count as an hacktoberfest contribution 😉

**Comment by miracle-E** [comment]
Great. I just registered. Thank you @AceTheCreator

**Comment by iambami** [comment]
This looks good @miracle-E 

Kindly add the Figma link for easy access.

**Comment by miracle-E** [comment]
![Speaker](https://github.com/user-attachments/assets/78296566-7054-43ab-8da6-789e25fa712b)
Here's the link to the updated design: https://www.figma.com/design/a8yUZtAPXlmk1kYcjWH5Wb/Speaker-Announcement?node-id=1-15&t=dWU5eelDNV4qpCrp-1
