### ISSUE TITLE
Conference Overlay Design

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#377]
We need an overlay design for the break session during the event. A design will be on the screen during breaks and when speakers prepare to come on stage.

### Previous Overlay Design

![image](https://github.com/user-attachments/assets/75414007-280d-4773-8e74-5cdb0bf990ac)

# Please Follow 👇🏿

## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

## Dimensions 
 1920x1080px

Make sure to share the Figma Link to your design.

**Comment by iambami** [comment]
For the in-session. This is what I'm talking about. 

You can watch the video [here](https://www.youtube.com/watch?v=YQYmTuVwQN8&t=20s) for more context.


![Image](https://github.com/user-attachments/assets/153921ef-a8dd-44ce-975d-49bff501e2e4)

**Comment by iambami** [comment]
Our platinum sponsors are [Postman](https://www.postman.com/) and [Gravitee](https://www.gravitee.io/).

**Comment by thulieblack** [comment]
We also need the following overlay design when speakers prepare to come on stage.

### Previously used 
![image](https://github.com/user-attachments/assets/4e1161f7-d1e1-4508-b171-80d67fa1a17e)

**Comment by nwanduka** [comment]
I'd like to work on this issue.

**Comment by Mayaleeeee** [comment]
Please go ahead!

**Comment by nwanduka** [comment]
What do you think of these? @Mayaleeeee @thulieblack @iambami 

![Conference Overlay - 1](https://github.com/user-attachments/assets/89aa388c-6a60-487f-947d-eb6486191c55)

![Conference Overlay - 2](https://github.com/user-attachments/assets/890f9a44-6cef-4edc-8552-0c39fbf3807b)

**Comment by nwanduka** [comment]
Any comments on these designs @Mayaleeeee @thulieblack @iambami

**Comment by Mayaleeeee** [comment]
> Any comments on these designs @Mayaleeeee @thuli,eblack @iambami 

Hey @nwanduka 

Thank you so much for your contributions! I'm sorry I didn't catch the notification about the updated design earlier.

I like the second design. It looks great, but I think it could use a few tweaks:

- The background colour you chose for the sponsors makes it a bit difficult to see the Postman logo text. Maybe![Screenshot_20240924_113334_GitHub.jpg](https://github.com/user-attachments/assets/4cb7d12d-9eb8-4285-9548-7c9ab0bb5969)

 we could adjust the colour just a little bit to make it more visible.

**Comment by nwanduka** [comment]
Right. I see what you mean. I've made some adjustments. I increased the opacity and i think it's better now. Here are the revised designs.

![Conference Overlay - 1 (revised)](https://github.com/user-attachments/assets/90200af5-0bd7-42f9-bcb2-fcc1b4d48d87)

![Conference Overlay - 2 (revised)](https://github.com/user-attachments/assets/307982a2-00ff-40d4-8249-0720c0a80d41)

**Comment by Mayaleeeee** [comment]
> Right. I see what you mean. I've made some adjustments. I increased the opacity and i think it's better now. Here are the revised designs.
> 
> ![Conference Overlay - 1 (revised)](https://github.com/user-attachments/assets/90200af5-0bd7-42f9-bcb2-fcc1b4d48d87)
> 
> ![Conference Overlay - 2 (revised)](https://github.com/user-attachments/assets/307982a2-00ff-40d4-8249-0720c0a80d41)
> 

It's still the same thing here.
Maybe you should try using a different colour for the background.

**Comment by nwanduka** [comment]
Okay. How's this?

![Conference Overlay - 1 (revised)](https://github.com/user-attachments/assets/ca45d3da-a0e5-4c1a-908e-f35629bc3b51)

![Conference Overlay - 2 (revised)](https://github.com/user-attachments/assets/27aa3950-ee32-49f0-9ea9-fe2c2440e789)

**Comment by Mayaleeeee** [comment]
> Okay. How's this?
> 
> ![Conference Overlay - 1 (revised)](https://github.com/user-attachments/assets/ca45d3da-a0e5-4c1a-908e-f35629bc3b51)
> 
> ![Conference Overlay - 2 (revised)](https://github.com/user-attachments/assets/27aa3950-ee32-49f0-9ea9-fe2c2440e789)
> 
> 

Perfect 👌 👍 
Thank you!

**Comment by Mayaleeeee** [comment]
> > Okay. How's this?
> > 
> > ![Conference Overlay - 1 (revised)](https://github.com/user-attachments/assets/ca45d3da-a0e5-4c1a-908e-f35629bc3b51)
> > 
> > ![Conference Overlay - 2 (revised)](https://github.com/user-attachments/assets/27aa3950-ee32-49f0-9ea9-fe2c2440e789)
> > 
> > 
> 
> Perfect 👌 👍 
> Thank you!

Let's go with Option B.

**Comment by thulieblack** [comment]
hey @nwanduka, this looks good thanks

**Comment by AceTheCreator** [comment]
@nwanduka  @thulieblack @Mayaleeeee I'm adding the #hacktoberfest label to this. @miracle-E kindly register at https://hacktoberfest.com/ to make it count as an hacktoberfest contribution 😉

**Comment by nwanduka** [comment]
Awesome. I just registered. Since this is a non-code contribution, how do i create a PR so that it counts towards my hacktoberfest contributions?

**Comment by AceTheCreator** [comment]
> Awesome. I just registered. Since this is a non-code contribution, how do i create a PR so that it counts towards my hacktoberfest contributions?

cc @Mayaleeeee

**Comment by AceTheCreator** [comment]
@nwanduka, If you’re submitting low- or non-code content to projects, make sure to create a PR to track your contribution.
