### ISSUE TITLE
The conference countdown banner

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#378]
We need a 2-day countdown banner for social media from Monday to the D-day. The idea behind this is to drop a constant reminder on social media till the day of the event. We could do a 5-day countdown banner as well

# Please Follow 👇🏿

## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design

**Comment by miracle-E** [comment]
Hi @thulieblack  I'd like to work on this issue.

**Comment by thulieblack** [comment]
Please go ahead

**Comment by miracle-E** [comment]
Kindly check out the banner designs here: https://www.figma.com/design/8syaKwF938ZrURIbkKWtiu/AsyncApi-Contributions?node-id=3801-21&t=NT30Ph7C4C23QWYj-1

**Comment by miracle-E** [comment]
Here's the draft. Please give feedback @thulieblack @Mayaleeeee 
![Design 1](https://github.com/user-attachments/assets/220fa215-12c0-41eb-8d18-be8ea64ca922)
![Design 2](https://github.com/user-attachments/assets/96dedf23-29e2-49a5-ba07-fdbfac03cdeb)
![Design 3](https://github.com/user-attachments/assets/ca97f722-b91d-4b18-943d-9f1f53f3630c)
![Design 4](https://github.com/user-attachments/assets/0a2eba54-944f-4c07-a6bc-ea60c16549f3)

**Comment by thulieblack** [comment]
Hey @miracle-E the countdown is for the Online Edition happening on the 30th of October

https://conference.asyncapi.com/venue/Online

**Comment by miracle-E** [comment]
Alright. Let me update the details. Thank you @thulieblack

**Comment by miracle-E** [comment]
_
![Design 1](https://github.com/user-attachments/assets/c48c3dd0-10c6-44d3-916c-f260981264cb)
![Design 2](https://github.com/user-attachments/assets/efca24b2-11ce-43ab-b0c3-3035b08b5d62)
![Design 3](https://github.com/user-attachments/assets/ffff2dc4-88b5-4d46-9ace-4408723e406a)
![Design 4](https://github.com/user-attachments/assets/d6893ab3-5b08-4c6b-abfe-d74c0d447754)
@thulieblack Kindly check_

**Comment by Mayaleeeee** [comment]
They all look great, @miracle-E however, we need to make a few adjustments:

- Please use 1200 x 675 for this design and all social media graphics.

I like the last design—it looks cool!
cc @iambami wdyt?

**Comment by miracle-E** [comment]
Thank you so much @Mayaleeeee 
I'll work on the dimension

**Comment by thulieblack** [comment]
looks amazing @miracle-E. Don't forget to adjust the dimensions on all banners

**Comment by miracle-E** [comment]
![Design 1](https://github.com/user-attachments/assets/e5d66082-8d90-4bef-a264-04ef7c35efdc)
![Design 2](https://github.com/user-attachments/assets/600c462b-7a3e-4455-8b48-9b3aacada9d6)
Thank you @thulieblack I have adjusted the dimensions

**Comment by thulieblack** [comment]
Can you please add 1 day to go and the one for D-Day

**Comment by miracle-E** [comment]
@thulieblack Which of the designs are we going with so I can make the necessary adjustments.

**Comment by thulieblack** [comment]
mmmh I'm not sure cc @Mayaleeeee

**Comment by Mayaleeeee** [comment]
> ![Design 1](https://github.com/user-attachments/assets/e5d66082-8d90-4bef-a264-04ef7c35efdc)
> ![Design 2](https://github.com/user-attachments/assets/600c462b-7a3e-4455-8b48-9b3aacada9d6)
> Thank you @thulieblack I have adjusted the dimensions

We'll be going with the first design here @miracle-E 

cc @thulieblack

**Comment by thulieblack** [comment]
So @miracle-E please create the remaining banners with the selected design

**Comment by miracle-E** [comment]
![Day1](https://github.com/user-attachments/assets/dcdfe102-aa44-4ad6-bf6b-835b1d2645f4)
![Dday](https://github.com/user-attachments/assets/731a5327-3e55-4253-bca4-7024f88da4be)

@Mayaleeeee @thulieblack

**Comment by thulieblack** [comment]
Thanks you so much @miracle-E

**Comment by iambami** [comment]
Thanks @miracle-E

**Comment by iambami** [comment]
@miracle-E 
Could you add "3 days to go" as well, please? Thank you.
