### ISSUE TITLE
A background for the restream

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#379]
This design will constantly be in the background throughout the event. Showcasing our platinum sponsors as the headline sponsor of the conference

### Previous Background

![image](https://github.com/user-attachments/assets/918e1e78-96f0-4643-bc5c-2c833f27838e)

### How its used
https://www.youtube.com/watch?v=SB15GgnEocE&list=PLbi1gRlP7pih0-GkQeQnkI_pQrTwlKrXZ

# Please Follow 👇🏿

## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

## Dimensions 
 1920x1080px

Make sure to share the Figma Link to your design

**Comment by Saurabhchaudhary9799** [comment]
hey @thulieblack  , do you want this frame exactly like past conference website
![Screenshot from 2024-09-06 22-01-34](https://github.com/user-attachments/assets/25c33c3c-9e04-4465-bfe1-4eefb67174bb)
![Screenshot from 2024-09-06 22-01-45](https://github.com/user-attachments/assets/5056790f-0bf9-487b-a524-2f3e0adcc93d)

**Comment by thulieblack** [comment]
No @Saurabhchaudhary9799 please check the issue description

**Comment by miracle-E** [comment]
![bg-restream](https://github.com/user-attachments/assets/d5b67350-c327-49f5-83eb-f0d7878bb300)
@thulieblack @Mayaleeeee I whipped something fast. I'll iterate and send more. Kindly check

**Comment by Mayaleeeee** [comment]
Thanks, @miracle-E 
The design looks good but needs a few adjustments.

- please add an overlay effect to the background to avoid distractions.
- we have two platinum sponsors - Postman and Gravitee.
- please use the colour of our sponsors' logos 

cc @iambami

**Comment by miracle-E** [comment]
Alright.. Thank you @Mayaleeeee 
I will make all necessary update

**Comment by miracle-E** [comment]
@Mayaleeeee Could you please help me with the sponsors' logos

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee Could you please help me with the sponsors' logos

Here you go @miracle-E 

https://www.gravitee.io/branding
![postman.png](https://github.com/user-attachments/assets/69694195-330f-4781-9e72-41826be7c518)

**Comment by miracle-E** [comment]
![bg-restream](https://github.com/use@Mayaleeeee ttachments/assets/947731ca-5277-4e39-bd48-0f9aeff26a4e)
Here @Mayaleeeee

**Comment by miracle-E** [comment]
![Restream](https://github.com/user-attachments/assets/d4be159b-402d-4e8b-a5db-f238a110a245)
This is another draft @Mayaleeeee

**Comment by miracle-E** [comment]
![bg-restream](https://github.com/user-attachments/assets/0599f001-96d7-4f1e-a147-f4a2c07f5179)
@Mayaleeeee

**Comment by thulieblack** [comment]
Hi @miracle-E so I tested the background on Restream, please adjust the AsyncAPI logo visible and make the logo text a bit smaller

![Screenshot_2024-09-25-20-05-21-751_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/c27b2a5f-a9df-4747-b595-a6f89c768888)


And I don't know maybe also lighten up the background it looks too dark, but that's my opinion 😉

**Comment by miracle-E** [comment]
Alright. Thank you for the feedback @thulieblack

**Comment by miracle-E** [comment]
![bg](https://github.com/user-attachments/assets/de5839db-c37a-444f-af57-c9fdb0a00812)
@thulieblack Kindly review.

**Comment by thulieblack** [comment]
![image](https://github.com/user-attachments/assets/62c9296a-80d2-4349-a882-6aa474ea8d68)

Much better but lets move the Platinum sponsor text to the side instead

**Comment by miracle-E** [comment]
Ooh, sorry about that @thulieblack 
I've updated the design
![Uploading rbg.png…]()

**Comment by AceTheCreator** [comment]
@miracle-E @thulieblack @Mayaleeeee I'm adding the #hacktoberfest label to this. @miracle-E kindly register at https://hacktoberfest.com/ to make it count as an hacktoberfest contribution 😉

**Comment by thulieblack** [comment]
thanks @miracle-E all good now

**Comment by miracle-E** [comment]
Alright. Thank you too @thulieblack 
@AceTheCreator Can I go ahead and create a PR for this contribution since I've registered for Hacktoberfest?

**Comment by AceTheCreator** [comment]
> Alright. Thank you too @thulieblack @AceTheCreator Can I go ahead and create a PR for this contribution since I've registered for Hacktoberfest?

Yes, please :)
