### ISSUE TITLE
Sponsor announcement design for social media

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#380]
We need a Sponsor announcement banner for Conference Financial Sponsors, Postman, and Gravitee. 

# Please Follow 👇🏿

## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design

**Comment by Mayaleeeee** [comment]
> Hi @thulieblack, I'd like to work on this issue. 

Please go ahead!

**Comment by nwanduka** [comment]
Please correct me if I'm wrong, but I noticed that there may already be an existing design for the sponsorship announcement.
https://x.com/AsyncAPISpec/status/1828402190311932000

If there is, could you share the Figma file with me so that I can create a banner for Gravitee? @Mayaleeeee @thulieblack

**Comment by thulieblack** [comment]
@iambami do you have specific requirements of how this should look?

But definitely not the same design as the Initiatives Sponsors

**Comment by Mayaleeeee** [comment]
> I'd like feedback on this draft. @thulieblack @Mayaleeeee @iambami
> 
> ![Postman](https://github.com/user-attachments/assets/e846ddfa-3c69-44ef-a83e-9c5076bd5306)
> 
> ![Gravitee](https://github.com/user-attachments/assets/cfc3efd2-5dde-48e1-a510-5f2232cb0073)
> 

Thanks @nwanduka 

What font did you use for the text 'AsyncAPI on Tour...' it looks small, kind of.

Could you please use a bigger font size?

**Comment by nwanduka** [comment]
Thanks for the feedback @Mayaleeeee. 

- I used 1200 x 675 pixels for the design
- I previously used the M3/headline/small font style. But I've changed it to M3/headline/large. I think it looks better now.
- I agree with what you said about the spacing between the logo and the Async on Tour text. I've reduced it. 
- I've put the two sponsors on one banner.

How do the changes look now?

![Financial Sponsors](https://github.com/user-attachments/assets/6c1d0bfb-48f7-47d8-9f38-e5136c779b91)

**Comment by Mayaleeeee** [comment]
> Thanks for the feedback @Mayaleeeee. 
> 
> - I used 1200 x 675 pixels for the design
> - I previously used the M3/headline/small font style. But I've changed it to M3/headline/large. I think it looks better now.
> - I agree with what you said about the spacing between the logo and the Async on Tour text. I've reduced it. 
> - I've put the two sponsors on one banner.
> 
> How do the changes look now?
> 
> ![Financial Sponsors](https://github.com/user-attachments/assets/6c1d0bfb-48f7-47d8-9f38-e5136c779b91)
> 

Thank you @nwanduka 

Looks better now!

cc @iambami

**Comment by thulieblack** [comment]
Please keep each sponsor logo separate and make one banner for each

**Comment by nwanduka** [comment]
> I'd like feedback on this draft. @thulieblack @Mayaleeeee @iambami
> 
> ![Postman](https://private-user-images.githubusercontent.com/122698422/366994518-e846ddfa-3c69-44ef-a83e-9c5076bd5306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTEyMjYsIm5iZiI6MTcyNzI5MDkyNiwicGF0aCI6Ii8xMjI2OTg0MjIvMzY2OTk0NTE4LWU4NDZkZGZhLTNjNjktNDRlZi1hODNlLTljNTA3NmJkNTMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxOTAyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmNjNzAwNmFhM2E4MmEyMGY4ZmE1YTA4NzQxZDI2OTUzZWIwNTkzOTVlMzAwNWNlODZmMTFjMGJmZGNkYmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YYGvRXdW9ytg1y_huknx5BUvrpNf452PZwGyaaxgPXQ)
> 
> ![Gravitee](https://private-user-images.githubusercontent.com/122698422/366998288-cfc3efd2-5dde-48e1-a510-5f2232cb0073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTEyMjYsIm5iZiI6MTcyNzI5MDkyNiwicGF0aCI6Ii8xMjI2OTg0MjIvMzY2OTk4Mjg4LWNmYzNlZmQyLTVkZGUtNDhlMS1hNTEwLTVmMjIzMmNiMDA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxOTAyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTEyYjY2MTBhZmQ2ZTc4N2EyNGE5YjEzZjQ2YzM0ZmE1YThjOTUyNzk0ZGFmMmNkMjhlZWExNTAxNDQ4YTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1U726V8Vx0s6dJZuOX-x5cU8yBjRZ7MCVi4DxeDp9Ec)

Hi @thulieblack, so these work then? Or are there any adjustments to be made?

**Comment by Mayaleeeee** [comment]
> > I'd like feedback on this draft. @thulieblack @Mayaleeeee @iambami
> > 
> > ![Postman](https://private-user-images.githubusercontent.com/122698422/366994518-e846ddfa-3c69-44ef-a83e-9c5076bd5306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTEyMjYsIm5iZiI6MTcyNzI5MDkyNiwicGF0aCI6Ii8xMjI2OTg0MjIvMzY2OTk0NTE4LWU4NDZkZGZhLTNjNjktNDRlZi1hODNlLTljNTA3NmJkNTMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxOTAyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmNjNzAwNmFhM2E4MmEyMGY4ZmE1YTA4NzQxZDI2OTUzZWIwNTkzOTVlMzAwNWNlODZmMTFjMGJmZGNkYmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YYGvRXdW9ytg1y_huknx5BUvrpNf452PZwGyaaxgPXQ)
> > 
> > ![Gravitee](https://private-user-images.githubusercontent.com/122698422/366998288-cfc3efd2-5dde-48e1-a510-5f2232cb0073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTEyMjYsIm5iZiI6MTcyNzI5MDkyNiwicGF0aCI6Ii8xMjI2OTg0MjIvMzY2OTk4Mjg4LWNmYzNlZmQyLTVkZGUtNDhlMS1hNTEwLTVmMjIzMmNiMDA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxOTAyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTEyYjY2MTBhZmQ2ZTc4N2EyNGE5YjEzZjQ2YzM0ZmE1YThjOTUyNzk0ZGFmMmNkMjhlZWExNTAxNDQ4YTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1U726V8Vx0s6dJZuOX-x5cU8yBjRZ7MCVi4DxeDp9Ec)
> 
> Hi @thulieblack, so these work then? Or are there any adjustments to be made?

No @nwanduka 
That can not work because the title 'AsyncAPI...' is small


Edit this (the one below) so we can have separate banners for our two sponsors.
 ![Screenshot_20240925_201559_Samsung Internet.jpg](https://github.com/user-attachments/assets/4129d729-b990-4d6f-9f6e-b8d353837f1b)

**Comment by nwanduka** [comment]
You're right @Mayaleeeee. I've put all the feedback into these revised designs. How is it now? @Mayaleeeee @thulieblack 

![Gravitee (revised)](https://github.com/user-attachments/assets/6c1fe757-3bf7-4742-902d-ceb0c986200e)

![Postman (revised)](https://github.com/user-attachments/assets/53a977c4-790e-4820-aade-eddc64edc10e)

**Comment by Mayaleeeee** [comment]
> You're right @Mayaleeeee. I've put all the feedback into these revised designs. How is it now? @Mayaleeeee @thulieblack 
> 
> ![Gravitee (revised)](https://github.com/user-attachments/assets/6c1fe757-3bf7-4742-902d-ceb0c986200e)
> 
> ![Postman (revised)](https://github.com/user-attachments/assets/53a977c4-790e-4820-aade-eddc64edc10e)
> 

Looks good!
Thank you

**Comment by iambami** [comment]
The design looks good. Thank you @nwanduka

**Comment by iambami** [comment]
Hey @nwanduka 

I am having a blocker with these images. .svg is not supported by  Buffer and image converter is messing it up as well.
Can I have the images locally or the Figma link? Thank you.
