### ISSUE TITLE
[BUG] Content inside Button not alligned correctly

### ISSUE THREAD

**Issue by catosaurusrex2003** [asyncapi/conference-website#389]
### Describe the bug.

Upon close inspection of the "Become a sponsor now" button on the website (as shown in the attached image)
![image](https://github.com/user-attachments/assets/5c42d81b-8926-4b03-975a-e05ae9a498df)
It is evident that the text is not perfectly aligned within the button. Although this is a subtle detail, it noticeably detracts from the visual polish and overall user experience.

This is happening because the button component is not able to handle longer 

I think the impact of this is high as a potential sponsor is going to interact with this button.

### Expected behavior

After changes in the button.js
![image](https://github.com/user-attachments/assets/45c6169a-2d8d-4867-9f6f-c80c1ef3ea53)

### Screenshots

Added above

### How to Reproduce

noticable on [https://conference.asyncapi.com/](https://conference.asyncapi.com/)

### 🥦 Browser

Other
This is happening in FIrefox only as of now, But it will eventually break in all browsers when the text size increases inside the button.

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by TenzDelek** [comment]
@catosaurusrex2003  in which screen size cause i dont see it in my machine. 
<img width="617" alt="image" src="https://github.com/user-attachments/assets/f88e1719-2917-4f07-a34d-4cd6d3a56e41">

**Comment by catosaurusrex2003** [comment]
1920 x 1080 (16:9) Firefox

this issue happens in firefox only for this button exactly.

But when you increase the text in the button then it maligns in both chrome and firefox.

**Comment by catosaurusrex2003** [comment]
ohk i figured out why the fonts were not working correctly as expected

the google fonts were not correctly imported in the `global.css`

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400&family=Work+Sans:wght@300;400;500;600;700&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@700&display=swap');

```
Before 👆 : this didnt import the google fonts correctly

```css
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&family=Inter:wght@300;400&family=Work+Sans:wght@300;400;500;600;700&display=swap');
@tailwind base;
@tailwind components;
@tailwind utilities;
```
After 👆 : this imports the google fonts correctly and all the fonts have been put in one import statement.


This solves the immediate issue of the button misalgning in firefox for now. but it will misallign again if the length of text is increased inside the button.
