### ISSUE TITLE
Stop Homepage Carousel Movement for Fewer Events

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#397]
Currently, the homepage carousel continues to scroll even when there are only a few events, which makes it quite noticeable that the same content is looping. To improve the user experience, it might be better to stop the carousel from moving when there are fewer events to display. This way, the repetition won't be as obvious, and it will create a smoother experience for users.

**Comment by J11tendra** [comment]
I would love to work on this issue. Can you please assign me this issue?

**Comment by AceTheCreator** [comment]
@J11tendra we don't assign issues, please go ahead and work on it :)
