### ISSUE TITLE
Add Online Speaker Images 

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#408]
### Why do we need this improvement?

Start adding online speakers images on the conference website.These are the speakers that will speak during the online conference

### How could it be implemented/designed?

This is the current list of the speakers and get their images from linkedIN:

1. Hari Krishnan - https://www.linkedin.com/in/harikrishnan83/
2. Yuan Yuan - https://www.linkedin.com/in/yuanyuanvassar/
3. Ivan Garcia Sainz-Aja - https://www.linkedin.com/in/ivangarciasainzaja/
4. Atinuke Oluwabamikemi Kayode - https://www.linkedin.com/in/atinuke-oluwabamikemi-kayode-5b838b1b7/
5. Aishat Muibudeen - https://www.linkedin.com/in/aishatmuibudeen
6. Thulisile Sibanda - https://www.linkedin.com/in/v-thulisile-sibanda/
7. Ankit Dash - https://github.com/helios2003
8. Giri Venkatesan - https://www.linkedin.com/in/girivenkatesan/

**Comment by techmannih** [comment]
@thulieblack  can I work on this issue?

**Comment by thulieblack** [comment]
Go ahead

**Comment by techmannih** [comment]
@thulieblack  how are looking?
![Screenshot 2024-10-02 222842](https://github.com/user-attachments/assets/fea624d2-8994-4a0e-aeb0-a93562ea4515)

**Comment by thulieblack** [comment]
Please add all the titles and please get some of them from the 2023 conference page

**Comment by techmannih** [comment]
@thulieblack  there are no for Atinuke Oluwabamikemi Kayode, Aishat Muibudeen, Thulisile Sibanda and Ankit Dash

**Comment by yashsaraswat2004** [comment]
Can I work on this?

**Comment by ashmit-coder** [comment]
> Can I work on this?

Sorry @yashsaraswat2004 but @techmannih already has a pr opem on the issue.

**Comment by yashsaraswat2004** [comment]
no worries
