### ISSUE TITLE
Online Conference YouTube Banner

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#411]
We need a YouTube banner to promote the online conference live stream

Please Follow 👇🏿
## AsyncAPI Branding Guidelines
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

## AsyncAPI Design System
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design

**Comment by techmannih** [comment]
@thulieblack  can I work on this issue

**Comment by thulieblack** [comment]
This is a design issue, not a code related issue

**Comment by techmannih** [comment]
@thulieblack okay, got it. Thank you!

**Comment by chiragkpoojary** [comment]
@thulieblack Hi! I noticed that the project doesn't currently include Docker. Would Docker be helpful for this project? I'd love to hear your thoughts!

**Comment by AceTheCreator** [comment]
> @thulieblack Hi! I noticed that the project doesn't currently include Docker. Would Docker be helpful for this project? I'd love to hear your thoughts!

I don't see any reason why we'll want to have docker on this project 🫠

**Comment by TenzDelek** [comment]
@thulieblack  can I have more detail on it, whether we need to put sponsers or any specific text ( timeline and header). 
also do we have prev year design for reference. it would be helpful to get more insight to design swiftly

**Comment by iambami** [comment]
@thulieblack, where can I find this design? I need it for the YouTube Playlists.

**Comment by iambami** [comment]
@thulieblack ?
