### ISSUE TITLE
Add link for London talks to the resources page

### ISSUE THREAD

**Issue by thulieblack** [asyncapi/conference-website#425]
### Why do we need this improvement?

Add the YouTube link for the recorded London talks to the resources page

https://youtube.com/playlist?list=PLbi1gRlP7pig77jJD2ER9wfTxPSzBrLW5&si=YPmjUsj5mU6FpLhB

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by toffee-k21** [comment]
Hi, @thulieblack could you please specify where to add the link, is it the top right corner where the London slides are?

![Screenshot 2024-10-16 233926](https://github.com/user-attachments/assets/a42dcddb-f47f-45ad-813f-e838adcd5799)

**Comment by thulieblack** [comment]
yes @toffee-k21
