### ISSUE TITLE
Links in the Resources Hub Should Open in a New Window

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#434]
Currently, the links in the "Resources Hub" navigation menu open in the same window, which can interrupt the user's flow when navigating through the site. To improve user experience, these links should open in a new tab/window.

**Comment by mrhat05** [comment]
can you assign me for this?

**Comment by Aryan4884** [comment]
@AceTheCreator please assign me the issue

**Comment by AceTheCreator** [comment]
We do not assign issues folks, please go ahead and open a PR if there's no opened pr already
