### ISSUE TITLE
[FEAT]Make Sponsor Logo Images Clickable with Links to Sponsor Websites

### ISSUE THREAD

**Issue by anmolyadav-dev** [asyncapi/conference-website#446]
### Why do we need this improvement?

- Enhanced Sponsor Visibility: Increases value for sponsors by directing traffic to their sites.
- Improved User Experience: Aligns with standard web navigation, making the site more intuitive.

### How will this change help?

 Increases visits to sponsor websites directly from our site.

### How could it be implemented/designed?

add Link to each image with there corresponding website

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator Shall we go ahead with this feature? :thinking:
