### ISSUE TITLE
Thank you design for the success of the AsyncAPI online conference.

### ISSUE THREAD

**Issue by iambami** [asyncapi/conference-website#450]
We need a thank you design to our sponsors, speakers, attendees and volunteers for the success of the AsyncAPI online conference.

### Please Follow 👇🏿
**AsyncAPI Branding Guidelines**
Link to the branding guidelines: [Branding Guidelines](https://github.com/asyncapi/brand/blob/master/brand-guidelines/README.md)

**AsyncAPI Design System**
Link to the design system: [Design System](https://www.figma.com/design/cFsY4LCfKmDqdlaTIJPpA1/Design-System?node-id=2-2&t=lvzQ4of9HnPsxHM4-1)

Make sure to share the Figma Link to your design

**Comment by miracle-E** [comment]
Working on it @iambami

**Comment by miracle-E** [comment]
![ThankYouPost](https://github.com/user-attachments/assets/7d5e3c3b-9c6a-430f-8801-112f6cc689fa)
Here's the link to the file on Figma @iambami

**Comment by iambami** [comment]
@thulieblack 

This is good yeah?

**Comment by Mayaleeeee** [comment]
Thank you, @miracle-E 

The design looks great. However, please reduce the effects you used on the 'Thank You' word. It's too much.


cc @iambami @thulieblack

**Comment by miracle-E** [comment]
![ThankYouPost2](https://github.com/user-attachments/assets/e0c53e7c-a340-4d27-944a-c69e269338e4)
Thank you @Mayaleeeee Here's an updated version

**Comment by Mayaleeeee** [comment]
> ![ThankYouPost2](https://github.com/user-attachments/assets/e0c53e7c-a340-4d27-944a-c69e269338e4)
> Thank you @Mayaleeeee Here's an updated version

Thank you @miracle-E 🙏

This is better. cc @iambami

**Comment by thulieblack** [comment]
Nicee!!! @miracle-E

**Comment by iambami** [comment]
Thanks @miracle-E
