### ISSUE TITLE
Embed the recording of the online conference

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/conference-website#452]
It would be great if we could replace the online venue header with a recording of the conference. This would make it easier for attendees to rewatch sessions directly from the main page!

**Comment by SagarSharma2809** [comment]
Great idea, this will improve the user experience and the online edition page will look more dynamic and engaging. We can directly embed the youtube video between header and agenda. I am willing to work on this issue.

**Comment by ashmit-coder** [comment]
Hey @AceTheCreator which online header are we exactly talking about. Some kind of image guiding it would be of great help.🤔

**Comment by SagarSharma2809** [comment]
Hi @ashmit-coder I think its this one , the main online edition page header
![image](https://github.com/user-attachments/assets/0faaf8ea-4d1f-4905-99e8-bd4565394815)

**Comment by ashmit-coder** [comment]
> Hi @ashmit-coder I think its this one , the main online edition page header ![image](https://private-user-images.githubusercontent.com/108415064/382490246-0faaf8ea-4d1f-4905-99e8-bd4565394815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Njg0OTUsIm5iZiI6MTczMDU2ODE5NSwicGF0aCI6Ii8xMDg0MTUwNjQvMzgyNDkwMjQ2LTBmYWFmOGVhLTRkMWYtNDkwNS05OWU4LWJkNDU2NTM5NDgxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNzIzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjAxY2FhOWQzMmJkN2ZjYzRkOTc0ZGZlZGQ2OTFhMGVmYjNjYmYxOGM3YTVkYTFjZTc5MmZlZWM5NTI4MzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6EzX01uaqXATrcJX8UCmGcHOS6MaTmbU0T6fCNxo3eg)

ohh i see.

**Comment by ashmit-coder** [comment]
So shall we also overlay the text over the video in the background, of just embed the youtube iframe in the bannrer. What do you think @SagarSharma2809 ?
cc: @AceTheCreator

**Comment by SagarSharma2809** [comment]
I think text overlay will look a little cluttered on the thumbnail and when the video starts playing, we have to make it disappear. We could embed the iframe below the text or we could remove the text header altogether. What are your thoughts on this? @AceTheCreator @ashmit-coder

**Comment by AceTheCreator** [comment]
> I think text overlay will look a little cluttered on the thumbnail and when the video starts playing, we have to make it disappear. We could embed the iframe below the text or we could remove the text header altogether. What are your thoughts on this? @AceTheCreator @ashmit-coder

I think we should remove the content of the header entirely and replace it with the youtube recording

**Comment by SagarSharma2809** [comment]
@ashmit-coder are you working on this? I am willing to work too if assigned.

**Comment by ashmit-coder** [comment]
> @ashmit-coder are you working on this? I am willing to work too if assigned.

No @SagarSharma2809 you can work on it. Secondly we don't assign issues you can put up a pr directly.

**Comment by Manancode** [comment]
Kept the header and showed recordings below in [pr](https://github.com/asyncapi/conference-website/pull/472#issue-2666585401)

if this is not better i can switch to remove the header entirely and replace with embedded video player. please let me know
