### ISSUE TITLE
[FEATURE] Make hamburger menu sticky

### ISSUE THREAD

**Issue by r3yc0n1c** [asyncapi/conference-website#455]
### Why do we need this improvement?

The current menu in the mobile version of the site disappears when scrolling. This behavior negatively impacts user experience, as users must scroll back up to access navigation options. This disrupts the flow of browsing and makes it harder to quickly navigate between pages, especially on a content-heavy site.

### How will this change help?

Making the hamburger menu sticky will provide consistent and convenient access to navigation options, enhancing the overall browsing experience. Users will be able to navigate seamlessly without needing to scroll back up.

### Screenshots

![peek_1](https://github.com/user-attachments/assets/211ed1f4-96ee-4f48-8723-232f213cd977)

### How could it be implemented/designed?

1. Changing the CSS positioning of the menu from fixed to sticky
2. Adjusting the top offset to ensure proper alignment with the viewport.
3. Testing on various devices and screen sizes to ensure compatibility and responsiveness.

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by ashmit-coder** [comment]
That sounds great @r3yc0n1c , lets see how the implementation looks!
