### ISSUE TITLE
[BUG] Logical render error in agenda component

### ISSUE THREAD

**Issue by ashmit-coder** [asyncapi/conference-website#456]
### Describe the bug.

When we switch between multiple venue pages, the agenda component breaks.

### Expected behavior

The component should not have the extra "break", words that are visible.

### Screenshots

![image](https://github.com/user-attachments/assets/94bed987-cb29-49ed-ac66-2be8781a796a)

### How to Reproduce

1. Visit the venue pages.
2. Shift between the venue pages untill the error occurs.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by om2137** [comment]
as discussed on slack I would like to work on this

**Comment by ashmit-coder** [comment]
> as discussed on slack I would like to work on this

You can work on it, we dont assign issues here.

**Comment by AceTheCreator** [comment]
I can't seem to reproduce this error @ashmit-coder 🤔

**Comment by ashmit-coder** [comment]
> I can't seem to reproduce this error @ashmit-coder 🤔

[AsyncAPI-Conference.webm](https://github.com/user-attachments/assets/c812f007-f8f5-47df-bce2-0989bb511588)

**Comment by AceTheCreator** [comment]
I see, it only does it when you click on the online venue 👍🏾
