### ISSUE TITLE
[BUG] <description> Sponsor Logos missing in venue

### ISSUE THREAD

**Issue by TenzDelek** [asyncapi/conference-website#494]
### Describe the bug.

the sponsors logos are missing in the venue route

### Expected behavior

logo should be there

### Screenshots

<img width="743" alt="image" src="https://github.com/user-attachments/assets/037ee7e7-e05a-41cd-bec3-e96b8e8a77d6" />

### How to Reproduce

1. go to nav
2. click venue
3. scroll down

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by TenzDelek** [comment]
@thulieblack  is this on purpose or a bug?

**Comment by SahilDahekar** [comment]
@TenzDelek PR #480 fixes this issue.

**Comment by TenzDelek** [comment]
@SahilDahekar  thanks for the notice. closing as duplicate
