### ISSUE TITLE
Add Sponsors PDF in website

### ISSUE THREAD

**Issue by iamVP7** [asyncapi/conference-website#53]
#### Reason/Context

Please try answering few of those questions
- Why we need this improvement?
We need to add PDF in the website.

- How will this change help?
Sponsors can download Sponsorship details and share to their team before making decision.

- What is the motivation? 
Discussed in https://github.com/asyncapi/community/discussions/74

#### Description
Please try answering few of those questions
- What changes have to be introduced?
A file to be uploaded in attachments folder.

- Will this be a breaking change?
No.

- How could it be implemented/designed?
A button will be added below sponsors heading and above `WANT TO BECOME A SPONSOR?` text

**Comment by derberg** [comment]
fyi, we build preview for PR here too
