### ISSUE TITLE
Support opengraph tags

### ISSUE THREAD

**Issue by boyney123** [asyncapi/conference-website#57]
#### Reason/Context

I shared the link on Twitter, and noticed we didn't have any open graph tags.

Be great to get some open graph tags for the conference for nice media sharing on things like Slack, Twitter etc.

**Comment by DefCon-007** [comment]
This website might come in handy to generate the tags and preview them after images are ready.
https://metatags.io/

**Comment by mcturco** [comment]
@derberg going to put this together now, do you think we should make it the same theme as the conference web assets that were created [in this issue](https://github.com/asyncapi/community/issues/137)? I can put the date of the conference as well, or we can just keep it general and just have the logo and "Online Conference"

**Comment by derberg** [comment]
@mcturco no opinion really, up to you

**Comment by mcturco** [comment]
@boyney123 here is an OG image for the conference website!

![OGImage_1152x668](https://user-images.githubusercontent.com/60163079/140385289-cf5a358c-8083-428d-83bd-eb58a75b1d2b.jpg)

Let me know if you need anything else to cover this issue 😄

**Comment by derberg** [comment]
We definitely need someone to open up a PR and add it to the website 😅

**Comment by mcturco** [comment]
@derberg I wouldn't mind handling this, however I just forked the repo and it looks like the index.html file is in the `.gitignore` so I wont be able to make changes to that file. Going back through the commits, it seems like @fmvilas added it to the gitignore so maybe he can help. (Unless I am unaware of a different process that is being used to render the DOM elements)

**Comment by derberg** [comment]
Yeah we use PUG (please do not ask why 😅 ) there to structure the project and then it is compiled into HTML. Check out 'npm run dev' to start local dev server

**Comment by boyney123** [comment]
Yeah happy to help @mcturco , if you get stuck maybe we can pair on this 2moro if you want? I have no idea how to get it worked either might be fun :D

**Comment by mcturco** [comment]
I'm actually making some progress, but will be happy to share the process with you tomorrow anyways over a call @boyney123 ! Haha I have never used PUG in my life but it is interesting!

@derberg I am going to also include a meta title and description to the best of my ability which you will be able to review when I submit the PR. Maybe it can be something that is aligned with the Marketing that you have going on currently?

**Comment by derberg** [comment]
I just tried to use it and noticed we have a problem, the size of the image is super huge 😅 

<img width="559" alt="Screenshot 2021-11-05 at 09 37 42" src="https://user-images.githubusercontent.com/6995927/140482104-47d1fd07-6f7e-4142-ab81-2d26a12531f0.png">

Twitter also ignores it. So config wise, all is super perfect, it is just that the image must be much much smaller @mcturco

**Comment by mcturco** [comment]
@derberg Oops!! I will fix that right away and submit another PR
