### ISSUE TITLE
Potential improvements for 2022 Conference landing page

### ISSUE THREAD

**Issue by mcturco** [asyncapi/conference-website#96]
#### Reason/Context
It is great that we have a conference website already up, thank you to @AceTheCreator for fixing that together! I have a few ideas/suggestions on how we might be able to improve the site to better communicate to new visitors what the conference is and how they can get involved. 

#### 💡  Ideas
- I'm not sure if the title "Building the future of Event-Driven APIs Together." fully communicates that the website is for a conference. Maybe it would be better to have the actual words "AsyncAPI Conference 2022" as the biggest text and then we can have this line as a subheader?
- I'm thinking we can add a section below the top section that communicates a little bit about what the conference is, like a little more detail of the topics and such. I know we don't know yet what the topics are, but we could maybe write a little bit of copy that vaguely states the context and what to expect
- I think instead of the text `Click the button to start the survey` maybe we have some better call to action that says `Help us decide on a date and location for the 2022 conference`
- It might be a good idea to add links to our social media to "stay tuned for updates"
- I'm not sure what the process is like for getting speakers, but should we add a call to action to sign up to be a speaker?
- It would probably be a good opportunity on this website to show or have a link to some of the 2021 conference recordings
- If we have any sponsors lined up for this year, should we add sponsor logos to the site or are we waiting until all of that is confirmed?

Let me know what you all think about these ideas. If we like them, I would be happy to propagate them in a design mock-up. Keep in mind that every year we will have a "brand" or visual style to represent the conference, so I might ideate on some visuals that we can add to this website. I like the direction of this so far though! 😄 

cc: @derberg @AceTheCreator

**Comment by mcturco** [comment]
Hello 😄 

I have an updated art direction for the Conference 2022 more specifically for the website. I believe the sponsors section we will have to hide until we have set sponsors, but other than that we should be able to add the rest of the sections right away.

**Here is an image version of the design mock-up:**
![Conference Website - Large Desktop](https://user-images.githubusercontent.com/60163079/180839009-4bd23104-06fa-476d-8a6e-1de23facc80c.jpg)

**And here is a Figma Prototype that you can scroll through and click around in:**
https://www.figma.com/proto/ldUyQL53HBoQjEqaC1QGRr/Conference-2022-Website?page-id=12%3A377&node-id=12%3A379&viewport=445%2C473%2C0.25&scaling=scale-down&starting-point-node-id=12%3A379

Would love to hear some feedback!

cc: @AceTheCreator @derberg

**Comment by AceTheCreator** [comment]
@mcturco this is really cool and I really fell in love with the architectural design you did 😀

**Comment by magicmatatjahu** [comment]
@mcturco Holy s***!!! I envy that @AceTheCreator will implement it. Really awesome! ❤️

**Comment by magicmatatjahu** [comment]
@mcturco Great work (again 😄). I have some ideas to improve our conference website:

As we will have in a month (or 2) information who will attend with presentation maybe we should also have an additional section with the introduction of people who will be? It would also be a good idea to have a separate page for each person like `/person/{}` with a description of the person with social links and a description of the presentation. We could also create separate cards for each person and display them as og images (those images that appear in the preview when you paste a link into slack etc.). What about you think?

In addition, we will need a place for the schedule of our conference like last year - then we used some kind of app where we had a whole schedule given with dates and times and people could subscribe to that. It was an iframe but that is not a problem for me.

cc @derberg @AceTheCreator @alequetzalli

**Comment by derberg** [comment]
@magicmatatjahu the schedule that comes from the scheduling app comes from Linux Foundation services, so it includes not only the schedule but also:
- info about presenters
- the ability to login (anyone) and set up a personal schedule of talks they want to attend
- and some other fancy stuff like rating talks for example

So whatever we wanna build in this area, we should make sure we do not duplicate data on our website, and do double-work but reuse what we have come from other sources. This is the source of the iframe from last year -> https://asyncapi2021.sched.com so you can explore there what can be iframed, like for example this view of speakers https://asyncapi2021.sched.com/directory/speakers

If you do not like iframe, then let's get rid of it in 2023, but it is too late as there are more important things to do, more useful for the conference, like the "ticket" generator for people that register, so it is easier for them to share on social media that they are attending

---

Regarding subscribe functionality, @AceTheCreator keep in mind to not use initial solution with spreadsheet (the one we did for voting on the event) but talk to @fmvilas to get new segment in MailChimp, and he will also explain to you how using Netlify and Zapier he introduced "email subscription" in asyncapi.com

**Comment by magicmatatjahu** [comment]
Nice, I knew that this app showed the whole schedule but i didn't know that also the speakers. Ok then my previous comment is probably not valid.

**Comment by mcturco** [comment]
@magicmatatjahu Yeah, we did have this idea, as you mentioned in your edit, but we were wondering how we could automate this process as much as possible. If we are using that app where the speakers can log in and update their profile, you would hope that this app would have an API to retrieve this data, but I believe @derberg said there was no API available. 

IMO, regardless of what tool/app we use for this process, it would be the **most** ideal if each accepted speaker received an invite via email to update their speaker profile where they can enter all their information such as: Name, Title, Employer, Social Links, etc, and that their accepted talks would be listed under their names. With this information, it would be great to have a "Speaker Card Generator" where we have a set design template that the variables get applied to, and the speaker could download and share their speaker card.

Would we have this capability using the LF scheduling app?

**Comment by alequetzalli** [comment]
I am def curious to see where this all goes, what a neat design for the site this year too!!

**Comment by magicmatatjahu** [comment]
@mcturco 

> IMO, regardless of what tool/app we use for this process, it would be the most ideal if each accepted speaker received an invite via email to update their speaker profile where they can enter all their information such as: Name, Title, Employer, Social Links, etc, and that their accepted talks would be listed under their names. With this information, it would be great to have a "Speaker Card Generator" where we have a set design template that the variables get applied to, and the speaker could download and share their speaker card.
> 
> Would we have this capability using the LF scheduling app?

🤷🏼 I don't know, maybe @derberg will know that. Creating these cards won't be a problem (I think), but yeah, we need data for that.

**Comment by mcturco** [comment]
@derberg Gotcha, do you know if that spreadsheet automatically updates when changes are made from the app?

**Comment by derberg** [comment]
@mcturco unfortunately it does not. @alequetzalli has contact to a person that can do the fresh export for us. I mean, I have also, but yeah, I'm out soon 😄

**Comment by mcturco** [comment]
@derberg RIP. Haha, but I guess it is better than no data!
