### ISSUE TITLE
Update event details, hide form

### ISSUE THREAD

**Issue by mcturco** [asyncapi/conference-website#97]
#### Reason/Context
I believe we have a final decision on a conference date and location based on the responses from the survey, (per announcement on slack: https://asyncapi.slack.com/archives/C34F2JV0U/p1655800294158509) so I believe we should be able to make the following changes to the website for now until we roll out a new design:

- [ ] Add conference dates: `November 3-5, 2022`
- [ ] Add event location: `Barcelona, Spain`
- [ ] Hide survey and `Click the button to start survey` button

**Comment by derberg** [comment]
call for proposals is also ready https://linuxfoundation.smapply.io/prog/asyncapi_conference_2022/ so we need to add a super visible button to get it there on the website

**Comment by LakshyaSatpal** [comment]
Hey, is this issue open for contribution?

**Comment by mcturco** [comment]
Hey @LakshyaSatpal, looks like we are all set here in this issue. Thanks! 😄
